### ISSUE TITLE
Possible Implementation of Server Edit and External jsons?

### ISSUE THREAD

**Issue by BLSK** [joshiejack/Progression#11]
Hello Joshiejack,
I have been doing bits with your mod mainly on Single player till recently since I can now get it working on the Server...
I find the Default seems to keep deleting all the progress I keep doing.  I did make new tabs and those are holding their info... is it by design?, or a bug?(hoping not another bogus issue)

I do apologies if we got off on the wrong foot the other day.  My reading of errors is at the moment more limited than I would like... Most have been spot on as the Modpack I have designed has had its own fair share of little issues, but I normally have a crash report.

**Comment by joshiejack** [comment]
How/where are you doing this testing. It's keeping my progress fine. The only time you should run in to issues with saving is if you're playing offline, or an offline server etc. Which I won't support.

**Comment by BLSK** [comment]
I am testing on a Online Server through the community I am apart of...
I have been turning on the server when I get online to work on it...  Trying to hopefully flush out issues before I open it to people that are looking forward to it.
I'll ask the Owner of the Community about your Offline statement.  It shouldn't be since we don't allow random name players for security reasons.  I don't have an issue in Single player either way and possibly pasting the files from it to the progression file would work.  I only wish I had like a crash report or some indicator in console stating what was going on...  I really don't want to hypothesis I could be goofing up again XD.

I'll ask the Community Owner if he can fail to edit the Default Tab.

**Comment by joshiejack** [comment]
Oh ur editing on a server? That won't work. Editor is client only, you have to copy the json to the server.

**Comment by BLSK** [comment]
Oh...ok hmm... could that be a new function request then for it to be editable on a Server?  I know you mentioned Server files take Priority over Client on your minecraft.curseforge page.  I was hoping to have some slight differences between both.
I would mention though....Seems new tabs do allow editing(I see its Client Tabs not Server now that you brought up that gain the tabs)...at least it looks that way...unless its some kind of ghost info...would it be possible to gain the ability?  I was hoping to do hot fixes on the fly on the server...
If you decided not to look into it its cool... at least I know this much now.  Thanks XD  I'll look back tomorrow.  Thanks for the help.

I would see 2 advantage of it being server side...the command method...I was thinking of giving FE rank up commands to the Progression for a automatic Upgrade system.  Even maybe TP commands or something to that effect.  Not to mention when I update the modpack I could grab the setup right off the server.  Ranks Tab may be deleted during which Client update but yeah...

I was even hoping OPs of the server may like to have their own tabs and what not they could have for the 'Unique Setup' the Modpack is going for...and I do mean 'unique'.  The Modpack is right now 1 of a kind.  A few mods are being developed specifically to join the pack though I am sure the main mod I am working with another designer on would of course be posted once a fully functional build was ready.  The main coder has college so he is very busy.  The mod was a plugin we still utilize on one of the community servers but its not ready as I said... I am learning java to try and be a better help to him.  In the least I am a great Brainstormer and Visionary to him, but I may work on any of the Texturing he may need.

Anyways...

I am rambling...sorry XD
BLSK

EDIT:::::::::::::::::::::::::::::::::::::::::
Oh if you said sure...maybe add a permission node if need for players with node in creative not requiring OP but top people in the server may be able to utilize it if they wanted just by giving their rank that node.

Lastly:
If you were to... maybe make it so the criteria.json was generated per tab rather than all in 1 Json File?  No big deal as I have done a minor bit tamping with Json working with other mods that use them so I do understand them fairly well, but oo oo
External jsons!
Can the Criteria call external Jsons?  Can I code in External functions to call other jsons I make?  World it work?
I know a small bit as I said so could I do like this?
{
"tabs": [
"function": "external",
"file": "TabRanks.json"
},
{
next tab called
}
]
}
As long as they were allowed to be generated in the Progression Folder by your code of course...would it work?

**Comment by joshiejack** [comment]
The only advantage making it work on a server has, it that you wouldn't have to be lazy. (It isn't exactly hard to copy the file to the server after you've edited it...) It gets synced to the clients when they login anyways. Only one person would be able to edit it at a time. So there's no benefit of working as a team on it. In order to make it possible for more than one possible. I would have to have 500 different packet types, to send every little different type of changes to the data. Which I am not going to do.

There's no chance of the json being different server/clientside, that would break things. The best bet is that I'll allow you to hide/unhide tabs based on criteria. Which I haven't done yet for some reason, thought I had >.>. (As in you can give individual players a special criteria that would unlock a tab specificially for them).

**Comment by BLSK** [comment]
I am not sure I would use a term lazy.  but would an external json setup be possible.  It isn't a huge bother to copy the adjustments from other jsons to a single json as I have had my dealings with it but with an external setup it would in some ways allow a more convenient transfer of data.  I am not trying to be badgering or anything cause I am liking the mod.  Now that the Client/Server thing is explained I will be able to fly more steadily.  I do appreciate the info at the very least...  It explains a fair bit.

**Comment by joshiejack** [comment]
Huh. I would. The only difference is typing a command to sync client>server (no chance of automatic) vs copying it manually. All it does is save a few seconds of someones time. It's on the todolist but way down in priority.

**Comment by BLSK** [comment]
Oh maybe I read your post in the wrong context....happens at times XD  I thought you said I was being lazy having a request for 'Convience' to others...not just myself but anyone that found the mod like I did.
Honestly...Automatic wouldn't be good I know how things work and that could go very bad...I do appreciate your time.  My views are mainly only Objective as a whole.  Sure slight bias...  Thanks for your time XD.

**Comment by BLSK** [comment]
Oh... Would you like a List of the Mods I am using for any possible implementations?  Some of the mods I am using in the Modpack I am fairly sure are not in really any Modpack to date(some may but haven't really found a pack using them, some I did find a 1 or 2 but not many).  Mind you I said some...maybe 4 to 12...I just looked through your repository at some of the things in it... worst case it may make it more versatile towards the future.  Either way some of the mods are what I may call 'slightly out of view' at least to certain 'circles'.  Most may still be handled well without any help of course... but maybe?
