### ISSUE TITLE
Map Lock and add?

### ISSUE THREAD

**Issue by BLSK** [joshiejack/Progression#12]
I downloaded your 3.6 and I was disappointed in a few things.
Since you moved some options to the criteria instead of Options the world isn't what it was...crashed cause didn't notice it at first but I corrected it and tried out your 3.6 a fair bit.  I had like a 30 minute kicked out of single player world error when I tried to look up 'Ender' seemed to be corrected when I closed and reopened client....it was weird...but everything said...I can't reproduce it at the moment...thank god.  I don't have a crash report as it wasn't a crash but I will try and reproduce it so to find out what it said in full..but it was like 10k lines....maybe more...

3.6 changed the way blocks act not being presented as Bedrock-like,  I really liked the unbreakable aspect the mod had in 3.5.  I saw your closed error for another guy and saw you corrected something with 3.6 but yeah... I was curious if the way the blocks are defined could be reverted?
As I noticed too... Everything is enable and craftable if there isn't a quest that sets it up with your new new changes to the criteria and options.  I don't know if that is the intension but its cute it allows it.  Maybe it corrects the part towards the bottom....

Adds:
Type: all?
Testing out how the world is I find it a bit cumbersome having to specify 5 types for most anything.  as example:(been going back to the drawing board to understand your mod better)
I set up a quest to click a log to unlock modid:minecraft(kinda obvious why) and so I break it but no harvest drop.... so I would need that too so put it in.  crafting/furnace/harvestdrops/entitydrops/breakblocks so I could allow a person to pick up seeds, and what not...seems a bit inefficient.  Many mods/items have many of the properties plus there are utility mods that allow you to add say enderpearls or raw porkchops to say a Iron Ore(if I wanted...easily could) which would then mean up to all 5 just to unlock 1 mod, or just 1 item.
I will be unlocking groups of mods at times and having a quest right now that is way off the screen cause of typex5 just for 20 mods is ...boy...  Hope you understand.

'Condition Editor': Exclude/Deny Action:
I find once I activate something it can't be deactivated...unless I am doing something wrong.  For instance  If like a few quests later I decide ok you did enough by mining iron ore...you can do anything in minecraft so put in ModID: minecraft and then its all open but next quest says Diamond Sword unlock use and craft but...you can already use and craft Diamond Swords.... cause 5 types before say Minecraft unlocked...  I was wondering if we could have a 'Condition Editor' with say a Condition 'Exclude' or 'Deny Action' adding Conditions much the same way as results but reverse the action.  A user of the mod would be wise to have temp name saying Minecraft Unlock exclude Sword to keep their quests straight for further down the road but yeah.  Eitherway inputting each id is ok but there are potentially thousands if not millions of ids to filter through just so you can keep a Diamond Sword uncraftable.  Then type x 5 for everything.

Don't get me wrong the mod is working great.  I am enjoying it...  Sure 3.6 has its ... yeah ... I am not sure what to think...  The blocks all do a breaking action but rewind if you don't have the quest complete...I enjoyed the bedrock version unless there was a reason you changed it.  I reverted back to 3.5 since it was working better for me.
BLSK

**Comment by joshiejack** [comment]
The crash, was probably due to exactly that, and missing some options from the json. Which I didn't think about for people updating. As for the bedrock thing, that should be working, I don't remember changing anything to do with that :S. 

It's always defaulted to everything being craftable until something is added... With the option to disable everything. But that was moved from the config to the criteria, as it made no sense when syncing otherwise.

As for all the actions having an option to be under the same thing, I'm not sure. I'd probably be happy to have a "Allow Creation" and "Allow Collection" (first being crafting/furnace combined, and latter being Break/Drops combined/anything else relevant). But not one overall.

As for your crafting thing. That's how it works now... If you add multiple criteria for crafting something,   it requires them both to be completed. Unless I'm misunderstanding your request here...

**Comment by BLSK** [comment]
Maybe something happened but now 3.6 seems to have the Unbreakable...maybe goofed up XD  What does name: IGNORE mean though for things like 'Click Block'  'Oredic'? so wood\* or plank\* or something would work?  Haven't test it out but um...(More written down below on Unbreakable)

I was thinking... Could arguments or variables like Type: crafting be 'Condition Editor' so we have to still put them in 1 for each condition but they all fall under one result?  That's kinda what I meant... but um...

As for the crash... I am sure it was what I found but the 'Client Kickout of Map' wasn't... I hit 'e' and it kicked me out of map but no crash.  I was trying to search for Ender as in Ender pearl to see if I could use it.  It seems to be fine now...not sure what happened there but yeah...for 30 minutes I couldn't log in cause when I logged in it spiraled an insane amount of lines ...not sure as I said but it seems to work now...

But if I understand you right....If for instance I had a quest to craft Wooden Sword but another quest say the very next one had Modid(ignore everything else) it wouldn't allow Wooden Sword to be craftable cause of the 2nd quest unlocking Minecraft with the 5 types...am I wrong?  
Quest 1: Click Log: modid:IGNORE Unlock Wooden Sword, Planks, Sticks, Dirt, Grass, Tall Grass, Bench
Quest 2: Kill Pig: Unlock Minecraft x5 sadly

quest 2 says No to wooden Sword so it fails right?

You see what I mean?  That's what I meant by Condition Editor Exclude meaning Exclude Wooden Sword from craft/usable/whatever kinda thing...If you get what I mean.  Prevent some things from failing, but also be able to say exclude activation of Ender Pearl use till later if it was a further quest or heck...before quest! XD...I would hate to have to make say 2000 item results separate up to x5 not to mention...I have Millions of all things XD.  I could set up exta

I think for some reason you moving the Options to Criteria changed more than expected.

I put in trues for them last time but this time I went with default so they say False and now its Bedrock with false not true.  That's where I mixed up... so you did change it without knowing?  I just have been troubleshooting and now its bedrock again with falses versus trues.  But I seem to be able to craft wooden swords but not use them...I am fairly thoroughly confused  I think somehow it got goofed up?  Granted I did craft in Natura bench not vanilla...checking!  Ok cause Natura was active still it said you can craft in me.  I would of thought Wooden Sword wouldn't be craftable but quest 2 voids use of some things cause it has the stuff in it?

Ok have work so gotta run:

 But Modid seems to Override the Specific Item in Window right?  Why not put it at Top vs bottom as it effects everything else?  At bottom it feels like it should hold no value except after the rest of the stuff but it unlocks mods specifically.  Get what I mean?  The item still holds use I guess....for some reason it unlocks the whole mod...so modid:minecraft unlocks all of minecraft rather than just the specific block. Not to mention to get modid to work right still have to have a item of that mod.  Honestly glad though.  If leave it Ignore it does singles...But yeah...it holds so much power it feels out of place at bottom...and blah

Ok long sorry...cya

**Comment by BLSK** [comment]
Ok I think I may of reproduced one of the errors that crashes map but not client:
http://pastebin.com/qg5Egt0y
I disabled Natura with the Minecraft unlock quest I was working with.  Thinking maybe there was a way to make quests like Wooden Sword unlock work though Minecraft wasn't unlocked but didn't like that Natura Benches would allow crafting of wooden swords and so I exited book and boom....Crash of World.

Here's the Criteria.json just in case it could be relevant(maybe not but yeah)
http://pastebin.com/9mnfMGJu

that map at the very least is unable to be entered now...

**Comment by joshiejack** [comment]
The issue is Natura. They have the dumbest of item names.

Natura:Rare Sapling 3

That space is breaking everything. I'll have to dumb proof it.

**Comment by BLSK** [comment]
Funny!  Ok cool...I'll change it then, Ill find one that has no spaces, thanks for the help
spaces bad(remembering)

**Comment by joshiejack** [comment]
As for natura benches bypassing, i have to add support for each mod. The other way was just breaking too much.

**Comment by BLSK** [comment]
I don't mind... at least I know another thing to watch out for.  may help others in the future kinda thing
I fixed the criteria fairly fast after all

Oh as for the Natura thing...Players wouldn't be able to make them... By my Minetweaker Default:  All wood breaks into 4 sticks and 4 sticks makes Dark Oak Plank and 4 of them make of course a Vanilla Bench not Natura... I set that up many months ago cause We have Saw Mills so why not make a person get a Saw Mill or Equivalent to get 'The Real Planks'  So yeah a person would of unlocked a lot by then but yeah....After natura unlock they could craft stuff but shouldn't be able to use them.  Unless Usable is unlocked

**Comment by joshiejack** [comment]
Would you mind opening a NEW issue, with JUST the bugs/things to improve listed. And none of your additional '5000 million words that are irrelevant'. So that I can go through my issues and easily see what I need to do/fix. Right now this issue is just too confusing to remember everything.
