### ISSUE TITLE
[Possible Bug] 1.7.10-0.3.7 Criteria tool tips stack when hovering over multiple criteria

### ISSUE THREAD

**Issue by SnowShock35** [joshiejack/Progression#15]
Hi Joshie,

Quick bug to report (Well I believe it is a bug).
- Minecraft 1.7.10
- Forge 10.13.3.1420 (Latest at time)
- Progression 0.3.7

**Description**
So as the subject of the bug probably suggests when having multiple criteria's on top of one another the tooltip will stack downwards for however many of them there are. Inc an image to make more sense.

**Image**
![2015-05-31_00 47 01](https://cloud.githubusercontent.com/assets/8388680/7899908/c03f6db6-072f-11e5-9e46-e44670d3aa26.png)

**Comment by joshiejack** [comment]
FIXED FOR SEXY @SnowShock35 even though I am like a year late and in 1.8.9... That be the problems with not modding for a bit ;D
