### ISSUE TITLE
[Bug/Enhancement] Tab Positioning 

### ISSUE THREAD

**Issue by SnowShock35** [joshiejack/Progression#16]
Hey Joshie (Again :p),

I have a bug/enhancement to report for you.

**Bug**

Minecraft 1.7.10
Forge 10.3.13.1420 (Latest at time)
Progression 0.3.7

When creating tabs, if u create too many they will continue to be created and go off the page.
Here is an image to try and illustrate this.

**Image**
![2015-05-31_00 47 19](https://cloud.githubusercontent.com/assets/8388680/7900034/33c5b59e-0738-11e5-9ab8-9b82b43a7dac.png)

**Enhancement/Change**

Instead of having tabs across the sides possibly have them across the bottom so that way when u could scroll to the right when u run out of task pages.

**Comment by joshiejack** [comment]
I'm not sure how I'd like the look of them along the top/bottom. Would it be cruel of me to just limit the number of tabs?

**Comment by Yulife** [comment]
Yes ;p

**Comment by joshiejack** [comment]
Made a compromise. If the number of tabs exceeds the vertical space. Then they'll switch to using the horizontal format instead.
