### ISSUE TITLE
Popup Toggle location and writing overlapping

### ISSUE THREAD

**Issue by BLSK** [joshiejack/Progression#18]
The position of the Popuptoggle is aroundish 60 pixels off to the left of the popuptoggle text.  I can alter repeatability when clicking on Popup or true/false as well
Last...the writing got garbled up...
And um...as you see the location of the Icon/item/block does overlap writing normally...I was hoping you may be able to adjust that up a few extra pixels as it would not overlap on True/False from my Observation.

![progression tabbing](https://cloud.githubusercontent.com/assets/8443396/7975738/9b2469e2-0a3f-11e5-9ce1-ba1dd487396e.png)

**Comment by joshiejack** [comment]
Oh I see I did the maths the wrong way around on the popup toggle.
As for the items overlapping, I plan to redo the item editing so you'd be editing the match damage/nbt etc when selecting the item. (Would also be done in a way that you'd have more than one item under each result/requirement). Means it wouldn't be wasting so much space either.

As for the bottom half that's because of the addition of orename, so it's overlapping because of the long name. This will also be alleviated when I do the item editor.

**Comment by BLSK** [comment]
Cool heres the Paste of my sudden world kick I am not sure but I do use button 5/4 a lot when I am in TeamSpeak so it may be an issue with button adding?  Also could quests have that drag and scroll thing...I am loving that... but yeah... I think it currently kicks me out of client when I close book

http://pastebin.com/kpaHgBPX

**Comment by joshiejack** [comment]
Did I forget to add the click and drag for the criteria editor?

As for the crash, I'm not 100% sure what the issue is, but I've tried something, so try out this build:
http://joshiejack.uk:8080/job/Progression/28/

**Comment by BLSK** [comment]
Ok checking it out right now...give me a fewish mins
not hard right now to crash my world(not client) as I keep doing it but have the gist what actions are doing it as I mentioned above using buttons to scroll then hit esc and I tend to crash world anyways a few mins

**Comment by BLSK** [comment]
I can't seem to force myself to crash now.  I do wonder...is it intentional that 'right' click toggles it to grab and scroll to on?  I thought at first that might of been the issue um...the 4 and 5 also lock it to on till I left click...If you could it would be more convenient if it was click and drag with them not grab and drag(as I call it)

**Comment by joshiejack** [comment]
I didn't understand a word of that

**Comment by BLSK** [comment]
When I right click...it grabs the window and letting go of the button keeps it grabs so when I move the mouse it drags the window.  Same goes for button 4 and button 5 for the mouse.

Left click lets go of the window when you let go of the button.  the rest don't.  Its kinda confusing grabbing the window all the time particually when I use button 5 for my TeamSpeak talking to friends

Like to apologies in either case... its 1am and I am half asleep being up since 4 am ... I work at 6pm tonight so its kinda early to go to bed XD

**Comment by BLSK** [comment]
I think at the current setup I can finally call PVPE ready to be updated(already on there as Unlisted Public) on FTB... I have many other things to do... last night I asked the designer of FLORA if I may be allowed to Update the mod since he abandoned it a year ago.  The person said yes so.... gotta work on my mod and update FLORA

I will pay fairly close attention to your mod on my Beta Version on MultiMC as I would like to relay info I feel you may like to know.  At least I understand it way better than I did the first few times we had a conversation XD.  Thanks for the great work.

Oh one last thing......almost forgot  I just reset so I could show ya our Criteria Achievement thing...I did make it a bit long but it runs off XD... Thanks again and yes that Log is Cylinder Shaped not Cube

![2015-06-04_00 46 34](https://cloud.githubusercontent.com/assets/8443396/7977027/47ed0180-0a53-11e5-83ed-e8e471e3195e.png)

**Comment by joshiejack** [comment]
It's using vanilla achievement system, so can't do anything about running off, not without reimplementing myself, not sure worth it.

**Comment by BLSK** [comment]
It's cool.  Just something I noticed I figured you may like to know about and I figured out what you did yesterday... I just don't know that much just yet about modding.  I have my mod I am working on to learn, get the hang of it...and a person from the community I am apart of said FLORA was a great mod...turned out it 'was' abandoned so I asked for it partly for the learning xp... I can read code somewhat...but it will be a decent guideline to learn and analyze while I learn more about modding.  Either way it sounds like the perfect armor mod for my pack and yeah can't find a super hardcore armor mod so yeah... Worth my time to try... but yeah... thanks for your time XD

EIther way I have held back the Update to PVPE for an extra Month cause I found your mod...was trying to figure out how I may be able to set up a rank system where some mods are disabled earlier on but you can unlock them as you progress....You made this mod and I was like 'MY PRAYERS HAVE BEEN HEARD!!!!!!!!!!!!!' XD... I guess its poetic in that way?
