### ISSUE TITLE
Usage flag not working

### ISSUE THREAD

**Issue by Crestor123** [joshiejack/Progression#22]
I need to only disable crafting for usable items with no damage value, like torches.  I want only certain groups of players to be able to craft a variety of items, but I want all players to be able to use the items.  However, in the "Allow Action" reward, I can't do this; I can disable both crafting and usage, or allow both.  I experimented with the "matchDamage", "usage", and "crafting" flags with a torch, and found that only the "crafting" flag had any impact.  When false, I could both craft and place a torch, and when true, I could do neither.  None of the other flags affected this outcome.

Additionally, the I found the same issue with undamaged tools, but once they had a damage value, I could use the tool, but not craft it, which is exactly what I needed.

I'm not sure if this is a bug, or just a misunderstanding on my part.  If needed, I can supply a more in-depth report with screenshots.

**Comment by Crestor123** [comment]
The latest update that added the "Crafting" reward did not fix my issue, unfortunately.  The same bug applies to the "usage" and "crafting" flags in the new reward just as it did the "Allow Action" reward.  Feel free to contact me if you're having trouble replicating this issue.

**Comment by Not-February** [comment]
I don't know if this is still being looked at at all, but I would like to add that I am having the exact same issue. I want all users to be able to USE a given item, but only users who have fulfilled specific criteria to be able to CRAFT it. However, locking the crafting to specific choices via Progression also prevents anyone else from even using the item, regardless of whether "usage" is set to true or false. I have tried this with various different items to the same result.

**Comment by joshiejack** [comment]
Usage was more about being able to using in crafting recipes where as crafting was crafting it. Which I guess can be kinda confusing. I think I'll make usage do what you expect, and then add another flag for the using in crafting, which idk what i'll call yet xD.
