### ISSUE TITLE
Console spam and can't connect to server.

### ISSUE THREAD

**Issue by LuxusDarkangel** [joshiejack/Progression#25]
Client log is spamming this all the time and i cant connect to the server: http://pastebin.com/qNnZapmV
I don't know if this is a problem on your side or in steves addons side, but your name appears first :P, so hope i'm not wrong.
Using version 0.4.1

**Comment by GirafiStudios** [comment]
Have you done any "tweaking" with Progression?

**Comment by LuxusDarkangel** [comment]
No.

**Comment by longErste** [comment]
This happened to me too. Please help

**Comment by longErste** [comment]
Downgrade to 0.35 helps

**Comment by joshiejack** [comment]
Yeah the 0.4 version seems to have been less stable than the 0.3, 1.8.9 version should be better though, lots of improvements ^_^
