### ISSUE TITLE
TE Workbench Crash

### ISSUE THREAD

**Issue by LokiChaos** [joshiejack/Progression#27]
If I right-click a Thermal Expansion Workbench with progression installed, I get a crash.  

Can reproduce with just MC 1.7.10, Forge 1448, and the following mods:
-   CodeChickenCore-1.7.10-1.0.7.46-universal 
-   CoFHCore-[1.7.10]3.0.3-303 
-   NotEnoughItems-1.7.10-1.0.5.111-universal 
-   Progression-1.7.10-0.4.1 
-   ThermalExpansion-[1.7.10]4.0.3B1-218 
-   ThermalFoundation-[1.7.10]1.2.0-102

Default configs for all of the above.

Full log here: http://paste.ee/p/kX589

**Comment by thauthau** [comment]
same here 

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 03/10/15 20:38
Description: Exception in server tick loop

java.lang.NoSuchMethodError: cofh.thermalexpansion.block.device.TileWorkbench.getWorldObj()Lnet/minecraft/world/World;
    at cofh.thermalexpansion.gui.container.device.ContainerWorkbench.func_75130_a(ContainerWorkbench.java)
    at cofh.thermalexpansion.gui.container.device.ContainerWorkbench.<init>(ContainerWorkbench.java:57)
    at cofh.thermalexpansion.block.device.TileWorkbench.getGuiServer(TileWorkbench.java:309)
    at cofh.thermalexpansion.gui.GuiHandler.getServerGuiElement(GuiHandler.java:46)
    at cpw.mods.fml.common.network.NetworkRegistry.getRemoteGuiContainer(NetworkRegistry.java:243)
    at cpw.mods.fml.common.network.internal.FMLNetworkHandler.openGui(FMLNetworkHandler.java:75)
    at net.minecraft.entity.player.EntityPlayer.openGui(Unknown Source)
    at cofh.thermalexpansion.block.TileInventory.openGui(TileInventory.java:216)
    at cofh.thermalexpansion.block.BlockTEBase.func_149727_a(BlockTEBase.java:84)
    at net.minecraft.server.management.ItemInWorldManager.func_73078_a(Unknown Source)
    at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:556)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
    at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
    at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
    at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:111)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 906348528 bytes (864 MB) / 2173698048 bytes (2073 MB) up to 3817865216 bytes (3641 MB)
    JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 7, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 79 mods loaded, 79 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv3-alpha-7} [Applied Energistics 2 Core](minecraft.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.16} [Aroma1997Core](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.6.43} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.4.107} [Not Enough Items](NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
    UCHIJAAAA   <CoFH ASM>{000} [CoFH ASM](minecraft.jar) 
    UCHIJAAAA   battlegear2{1.7.10} [Mine & Blade Battlegear 2 - Bullseye](1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar) 
    UCHIJAAAA   bspkrsCore{6.15} [bspkrsCore]([1.7.10]bspkrsCore-universal-6.15.jar) 
    UCHIJAAAA   StartingInventory{1.7.10.r03} [StartingInventory]([1.7.10]StartingInventory-universal-1.7.10.r03.jar) 
    UCHIJAAAA   appliedenergistics2{rv3-alpha-7} [Applied Energistics 2](appliedenergistics2-rv3-alpha-7.jar) 
    UCHIJAAAA   bdlib{1.9.2.104} [BD Lib](bdlib-1.9.2.104-mc1.7.10.jar) 
    UCHIJAAAA   ae2stuff{0.5.0.56} [AE2 Stuff](ae2stuff-0.5.0.56-mc1.7.10.jar) 
    UCHIJAAAA   antiqueatlas{4.2.7-1.7.10} [Antique Atlas](antiqueatlas-4.2.7-1.7.10.jar) 
    UCHIJAAAA   CoFHCore{1.7.10R3.0.3} [CoFH Core](CoFHCore-[1.7.10]3.0.3-303.jar) 
    UCHIJAAAA   Railcraft{9.7.0.0} [Railcraft](Railcraft_1.7.10-9.7.0.0.jar) 
    UCHIJAAAA   ImmersiveEngineering{0.5.4} [Immersive Engineering](ImmersiveEngineering-0.5.4.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins188} [Mantle](Mantle-1.7.10-0.3.2a.jar) 
    UCHIJAAAA   ThermalFoundation{1.7.10R1.2.0} [Thermal Foundation](ThermalFoundation-[1.7.10]1.2.0-102.jar) 
    UCHIJAAAA   ThermalExpansion{1.7.10R4.0.3B1} [Thermal Expansion](ThermalExpansion-[1.7.10]4.0.3B1-218.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila](Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct](TConstruct-1.7.10-1.8.7.jar) 
    UCHIJAAAA   Armory{@VERSION@} [Armory](Armory-1.0.1.3-216-SNAPSHOT.jar) 
    UCHIJAAAA   Armory-Weaponry{@VERSION@} [Armory-Weaponry](Armory-Weaponry-1.0.0-18.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.16} [Aroma1997Core|Helper](Aroma1997Core-1.7.10-1.0.2.16.jar) 
    UCHIJAAAA   AromaBackup{0.0.0.5.b20} [AromaBackup](AromaBackup-1.7.10-0.0.0.5.b20.jar) 
    UCHIJAAAA   AromaBackupRecovery{1.0} [AromaBackup Recovery](AromaBackup-1.7.10-0.0.0.5.b20.jar) 
    UCHIJAAAA   BiblioCraft{1.11.2} [BiblioCraft](BiblioCraft[v1.11.2][MC1.7.10].jar) 
    UCHIJAAAA   CarpentersBlocks{3.3.7} [Carpenter's Blocks](Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
    UCHIJAAAA   chisel{2.5.1.44} [Chisel 2](Chisel2-2.5.1.44.jar) 
    UCHIJAAAA   CompactMachines{1.7.10-1.20} [Compact Machines](compactmachines-1.7.10-1.20.jar) 
    UCHIJAAAA   ComputerCraft{1.74} [ComputerCraft](ComputerCraft1.74.jar) 
    UCHIJAAAA   cookiecore{1.4.0} [Cookie Core](CookieCore-1.7.10-1.4.0-11.jar) 
    UCHIJAAAA   CraftHeraldry{1.1.3} [CraftHeraldry](CraftHeraldry 1.1.3.jar) 
    UCHIJAAAA   endercore{1.7.10-0.1.0.24_beta} [EnderCore](EnderCore-1.7.10-0.1.0.24_beta.jar) 
    UCHIJAAAA   EnderZoo{1.7.10-1.0.15.32} [Ender Zoo](EnderZoo-1.7.10-1.0.15.32.jar) 
    UCHIJAAAA   MetallurgyCore{4.0.4} [Metallurgy Core](MetallurgyCore-1.7.10-4.0.4.18.jar) 
    UCHIJAAAA   Metallurgy{4.0.8} [Metallurgy 4](Metallurgy-1.7.10-4.0.8.97.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft](Pam's HarvestCraft 1.7.10j.jar) 
    UCHIJAAAA   progressiveautomation{1.6.27} [Progressive Automation](ProgressiveAutomation-1.7.10-1.6.27.jar) 
    UCHIJAAAA   MineTweaker3{3.0.10} [MineTweaker 3](MineTweaker3-1.7.10-3.0.10B.jar) 
    UCHIJAAAA   TSteelworks{1.7.10-1.1.1} [Tinkers' Steelworks](TSteelworks-1.7.10-1.1.1-17.jar) 
    UCHIJAAAA   ExtraTiC{1.4.5} [ExtraTiC](ExtraTiC-1.7.10-1.4.5.jar) 
    UCHIJAAAA   ezstorage{1.1.0} [EZ Storage](ezstorage-1.1.0.jar) 
    UCHIJAAAA   fastleafdecay{1.1} [Fast Leaf Decay](FastLeafDecay-1.7.10-1.1.jar) 
    UCHIJAAAA   flansmod{4.10.0} [Flan's Mod](Flans Mod-1.7.10-4.10.0.jar) 
    UCHIJAAAA   Steamcraft{0.28.10} [Flaxbeard's Steam Power](Flaxbeard'sSteamPower-1.7.10-0.28.10.jar) 
    UCHIJAAAA   GraveStone{2.12.3} [GraveStone](GraveStone-2.12.4.jar) 
    UCHIJAAAA   iChunUtil{4.2.2} [iChunUtil](iChunUtil-4.2.2.jar) 
    UCHIJAAAA   immersiveintegration{0.5.4} [Immersive Integration](immersiveintegration-0.5.4.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks](InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   LoreExp{1.0.5} [Lore Expansion](LoreExpansion-1.7.10-1.0.5.B29a.jar) 
    UCHIJAAAA   mo{0.4.0-RC4} [Matter Overdrive](MatterOverdrive-1.7.10-0.4.0-RC4.jar) 
    UCHIJAAAA   MTRM{1.0} [MineTweakerRecipeMaker](MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
    UCHIJAAAA   ModularArmour{1.0.0} [Modular Armour](ModularArmour-1.7.10-1.0.18-41.jar) 
    UCHIJAAAA   NEIAddons{1.12.11.36} [NEI Addons](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Developer{1.12.11.36} [NEI Addons: Developer Tools](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.11.36} [NEI Addons: Applied Energistics 2](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.11.36} [NEI Addons: Botany](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.11.36} [NEI Addons: Forestry](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.11.36} [NEI Addons: Crafting Tables](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.11.36} [NEI Addons: Ex Nihilo](neiaddons-1.12.11.36-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.12} [NEI Integration](NEIIntegration-MC1.7.10-1.0.12.jar) 
    UCHIJAAAA   openmodularturrets{2.1.4-183} [Open Modular Turrets](OpenModularTurrets-1.7.10-2.1.4-183.jar) 
    UCHIJAAAA   Progression{0.4.1} [Progression](Progression-1.7.10-0.4.1.jar) 
    UCHIJAAAA   RedstoneArsenal{1.7.10R1.1.1} [Redstone Arsenal](RedstoneArsenal-[1.7.10]1.1.1-89.jar) 
    UCHIJAAAA   RArm{1.7.10-1.2.0-40} [Redstone Armory](RedstoneArmory-1.7.10-1.2.0-40.jar) 
    UCHIJAAAA   simplyjetpacks{1.5.1} [Simply Jetpacks](SimplyJetpacks-MC1.7.10-1.5.1.jar) 
    UCHIJAAAA   Sync{4.0.0} [Sync](Sync-4.0.0.jar) 
    UCHIJAAAA   ThermalCasting{0.0.3} [Thermal Casting](thermalcasting-0.0.3.jar) 
    UCHIJAAAA   ThermalDynamics{1.7.10R1.1.0} [Thermal Dynamics](ThermalDynamics-[1.7.10]1.1.0-161.jar) 
    UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips](TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHIJAAAA   tinkersdefense{1.2} [Tinkers' Defense](Tinkers-Defense-1.2.1.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.2} [Waila Harvestability](WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJAAAA   wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins](WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
    UCHIJAAAA   libsandstone{1.0.0} [libsandstone](LibSandstone-1.0.0.jar) 
    UCHIJAAAA   aobd{2.8.4} [Another One Bites The Dust](AOBD-2.8.4.jar) 
    UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks](IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
    AE2 Version: alpha rv3-alpha-7 for Forge 10.13.4.1448
    CoFHCore: -[1.7.10]3.0.3-303
    Mantle Environment: Environment healthy.
    ThermalFoundation: -[1.7.10]1.2.0-102
    ThermalExpansion: -[1.7.10]4.0.3B1-218
    TConstruct Environment: Environment healthy.
    RedstoneArsenal: -[1.7.10]1.1.1-89
    ThermalDynamics: -[1.7.10]1.1.0-161
    List of loaded APIs: 
        \* appliedenergistics2|API (rv2) from appliedenergistics2-rv3-alpha-7.jar
        \* Armory-API|Armor (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|core (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Crafting (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Crafting|SmithingsAnvil (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Crafting|SmithingsAnvil|Components (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Crafting|SmithingsAnvil|Recipe (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Events (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Events|Client (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Events|Common (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Item (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Materials (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* Armory-API|Registries (@API_VERSION@) from Armory-1.0.1.3-216-SNAPSHOT.jar
        \* BattlePlayer (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar
        \* Baubles|API (1.0.1.10) from GraveStone-2.12.4.jar
        \* BuildCraftAPI|core (1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* BuildCraftAPI|items (1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* BuildCraftAPI|statements (1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* BuildCraftAPI|tiles (1.1) from Railcraft_1.7.10-9.7.0.0.jar
        \* BuildCraftAPI|tools (1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* BuildCraftAPI|transport (4.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* CarpentersBlocks|API (3.3.7) from Carpenter's Blocks v3.3.7 - MC 1.7.10.jar
        \* ChiselAPI (0.1.0) from Chisel2-2.5.1.44.jar
        \* ChiselAPI|Carving (0.1.0) from Chisel2-2.5.1.44.jar
        \* ChiselAPI|Rendering (0.1.0) from Chisel2-2.5.1.44.jar
        \* CoFHAPI (1.7.10R1.0.10) from ImmersiveEngineering-0.5.4.jar
        \* CoFHAPI|block (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|core (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHAPI|energy (1.7.10R1.0.2) from OpenModularTurrets-1.7.10-2.1.4-183.jar
        \* CoFHAPI|fluid (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHAPI|inventory (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|item (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHAPI|modhelpers (1.7.10R1.0.13B2) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHAPI|tileentity (1.7.10R1.0.13) from ProgressiveAutomation-1.7.10-1.6.27.jar
        \* CoFHAPI|transport (1.7.10R1.0.13) from EnderCore-1.7.10-0.1.0.24_beta.jar
        \* CoFHAPI|world (1.7.10R1.0.13) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|audio (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|gui (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|gui|container (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|gui|element (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|gui|element|listbox (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|gui|slot (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|inventory (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|render (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|render|particle (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|util (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|util|helpers (1.7.10R1.0.3B3) from CoFHLib-[1.7.10]1.0.3-175.jar
        \* CoFHLib|util|position (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|world (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* CoFHLib|world|feature (1.7.10R1.0.3) from CoFHCore-[1.7.10]3.0.3-303.jar
        \* ComputerCraft|API (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|FileSystem (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|Lua (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|Media (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|Peripheral (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|Permissions (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|Redstone (1.74) from ComputerCraft1.74.jar
        \* ComputerCraft|API|Turtle (1.74) from ComputerCraft1.74.jar
        \* DualWield (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar
        \* ForestryAPI|apiculture (2.6.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|arboriculture (2.3.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|circuits (1.1.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|core (2.6.1) from GraveStone-2.12.4.jar
        \* ForestryAPI|farming (1.1.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|food (1.1.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|fuels (2.0.1) from GraveStone-2.12.4.jar
        \* ForestryAPI|genetics (2.7.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|hives (4.0.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|lepidopterology (1.1) from GraveStone-2.12.4.jar
        \* ForestryAPI|mail (3.0.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|recipes (2.1.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|storage (2.3.0) from GraveStone-2.12.4.jar
        \* ForestryAPI|world (1.1.0) from GraveStone-2.12.4.jar
        \* Heraldry (alpha) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar
        \* IC2API (1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* ImmersiveEngineering|API (1.0) from ImmersiveEngineering-0.5.4.jar
        \* MatterOverdrive|API (0.4.0-RC3) from MatterOverdrive-1.7.10-0.4.0-RC4.jar
        \* MetallurgyAPI (2.0.1) from Metallurgy-1.7.10-4.0.8.97.jar
        \* Quiver (0.2) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar
        \* RailcraftAPI|bore (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|carts (1.5.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|core (1.4.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|crafting (1.0.0) from ImmersiveEngineering-0.5.4.jar
        \* RailcraftAPI|electricity (1.6.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|events (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|fuel (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|helpers (1.1.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|items (1.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|locomotive (1.0.1) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|signals (1.3.4) from Railcraft_1.7.10-9.7.0.0.jar
        \* RailcraftAPI|tracks (2.0.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* Shield (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar
        \* Thaumcraft|API (4.2.2.0) from Railcraft_1.7.10-9.7.0.0.jar
        \* TSteelworksAPI (1.2) from TSteelworks-1.7.10-1.1.1-17.jar
        \* WailaAPI (1.2) from Waila-1.5.10_1.7.10.jar
        \* Weapons (0.1) from 1.7.10-MB_Battlegear2-Bullseye-1.0.8.1.jar
    AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:ON, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:OFF, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
    Profiler Position: N/A (disabled)
    Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    Player Count: 1 / 8; [EntityPlayerMP['thauthau'/388, l='New World', x=-150,15, y=75,00, z=286,47]]
    Type: Integrated Server (map_client.txt)
    Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by joshiejack** [comment]
Yeah I don't think my te support was very well done/tested in 1.7 >.>.
