### ISSUE TITLE
Cannot Save Things In Default Tab(Multiplayer)

### ISSUE THREAD

**Issue by Omuck3** [joshiejack/Progression#28]
Hi.  I put progression on my server to support the goal of building civilizations.  I wanted to make a criteria that requires someone to login 3 times.  The reward would the the research of: rough carpentry.  The rough carpentry research is required for tree chopping, and crafting of planks and sticks.  However, if I right click to get out of the edit criteria(in the default tab), it will remove the criteria.  If I try and get out via escape, it does the same.  The only solution is to use a new tab.  
Also, is it possible to have players choose what they want to unlock next?  For example, if I had Carpentry 1 and Stone Age both after Rough Carpentry(these are criteria names), could I have people choose what they want to unlock next.  That way specialization of skills would eventually be required...

Thanks!

**Comment by Crestor123** [comment]
Check the config file for progression; there's a flag that, by default, syncs the client's criteria file with the server's.  If you're editing the progression on a server, any changes you make will be erased when the server syncs its criteria file with the client's.  I would recommend editing the criteria in a single-player world and copying it to the server when you're finished.

As for choosing a profession, I looked into doing something similar on my server.  You can make two or more criteria conflict by clicking on the first, and then control-clicking on the second.  This allows you to prevent players from picking more than one path.  By making different requirements for each conflicting criteria, you can effectively make a class or profession system based on what the player chooses.

**Comment by Avarice** [comment]
Where/what is the flag you mentioned that sync's client criteria file with the server? My config looks like this:

> # Configuration file
> 
> settings {
>     B:"Add Recipe for Tile Entity Claimer"=true
>     B:"Enable Editing"=true
> }

and under /ipaddress

> {
>   "tabs": [
>     {
>       "uniqueName": "DEFAULT",
>       "displayName": "Default",
>       "sortIndex": 0,
>       "isVisible": true,
>       "stack": "minecraft:book",
>       "criteria": []
>     }
>   ],
>   "defaultTabID": "DEFAULT",
>   "disableCraftingUntilRewardAdded": false,
>   "disableUsageUntilRewardAdded": false,
>   "unclaimedTileCanCraftAnything": false,
>   "unclaimedTileCanUseAnythingForCrafting": false,
>   "interfaceItem": "minecraft:book",
>   "displayRequirementsOnNEIClick": true

**Comment by joshiejack** [comment]
These things you suggested should all be doable in the 1.8.9 version when it's released.
