### ISSUE TITLE
Fatal Error In Singleplayer?

### ISSUE THREAD

**Issue by Omuck3** [joshiejack/Progression#29]
I was making a "tech tree" in single player, planning on moving it to the server when I was done.  I had made a few criteria and linked some up.  Then out of nowhere, my world closed saying "A Fatal Error Has Occurred, This Connection Has Been Terminated".  When I went back into my world, all the criteria were still there.  Thinking it was a freak accident, I went back to adding criteria.  Then it happened again.  When I opened my world yet again, the criteria from before were gone.  What is going on?

**Comment by joshiejack** [comment]
No clue, the editor in 1.7.10 was very buggy, especially with saving. Hopefully thing will be improved in 1.8.9.
