### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by SinusoidalC** [joshiejack/Progression#30]
---- Minecraft Crash Report ----
// There are four lights!

Time: 7/30/15 9:06 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at joshie.progression.gui.GuiTreeEditor.drawForeground(GuiTreeEditor.java:100)
    at joshie.progression.gui.GuiBase.func_73863_a(GuiBase.java:64)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at joshie.progression.gui.GuiTreeEditor.drawForeground(GuiTreeEditor.java:100)
    at joshie.progression.gui.GuiBase.func_73863_a(GuiBase.java:64)

-- Screen render details --
Details:
    Screen name: joshie.progression.gui.GuiTreeEditor
    Mouse location: Scaled: (213, 119). Absolute: (426, 240)
    Screen size: Scaled: (427, 240). Absolute: (853, 480). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['SinusoidalC'/130, l='MpServer', x=-221.60, y=5.62, z=-1355.97]]
    Chunk stats: MultiplayerChunkCache: 228, 237
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-140,4,-1196), Chunk: (at 4,0,4 in -9,-75; contains blocks -144,0,-1200 to -129,255,-1185), Region: (-1,-3; contains chunks -32,-96 to -1,-65, blocks -512,0,-1536 to -1,255,-1025)
    Level time: 163096 game time, 210062 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 56 total; [EntityClientPlayerMP['SinusoidalC'/130, l='MpServer', x=-221.60, y=5.62, z=-1355.97], EntityPainting['画'/75, l='MpServer', x=-256.50, y=9.50, z=-1325.94], EntityBat['蝙蝠'/26, l='MpServer', x=-289.34, y=5.00, z=-1301.31], EntityBat['蝙蝠'/27, l='MpServer', x=-286.88, y=5.00, z=-1298.34], EntityBat['蝙蝠'/28, l='MpServer', x=-290.66, y=5.00, z=-1300.66], EntityBat['蝙蝠'/29, l='MpServer', x=-289.44, y=5.00, z=-1300.00], EntityBat['蝙蝠'/30, l='MpServer', x=-291.69, y=5.00, z=-1299.59], EntityVillager['村民'/31, l='MpServer', x=-298.91, y=5.00, z=-1278.63], EntityPainting['画'/57, l='MpServer', x=-285.50, y=9.50, z=-1290.94], EntityVillager['村民'/32, l='MpServer', x=-300.03, y=5.00, z=-1276.31], EntityVillager['村民'/35, l='MpServer', x=-291.13, y=5.00, z=-1278.25], EntityVillager['村民'/36, l='MpServer', x=-291.69, y=5.00, z=-1276.31], EntityVillager['村民'/49, l='MpServer', x=-278.50, y=4.00, z=-1311.69], EntityVillager['村民'/50, l='MpServer', x=-282.50, y=5.00, z=-1303.50], EntityVillager['村民'/51, l='MpServer', x=-284.53, y=5.00, z=-1298.31], EntityVillager['村民'/52, l='MpServer', x=-276.31, y=5.00, z=-1305.50], EntityBat['蝙蝠'/53, l='MpServer', x=-288.25, y=5.00, z=-1300.03], EntityBat['蝙蝠'/54, l='MpServer', x=-277.56, y=4.00, z=-1307.63], EntityVillager['村民'/55, l='MpServer', x=-277.69, y=6.00, z=-1301.31], EntityVillager['村民'/56, l='MpServer', x=-277.69, y=6.00, z=-1302.50], EntityPainting['画'/57, l='MpServer', x=-285.50, y=9.50, z=-1290.94], EntityItemFrame['entity.ItemFrame.name'/58, l='MpServer', x=-284.50, y=9.50, z=-1286.06], EntityItemFrame['entity.ItemFrame.name'/59, l='MpServer', x=-285.50, y=9.50, z=-1286.06], EntityItemFrame['entity.ItemFrame.name'/60, l='MpServer', x=-286.50, y=9.50, z=-1286.06], EntityVillager['村民'/61, l='MpServer', x=-280.59, y=4.00, z=-1287.50], EntityVillager['村民'/62, l='MpServer', x=-284.69, y=4.00, z=-1288.50], EntityVillager['村民'/63, l='MpServer', x=-284.94, y=4.00, z=-1292.50], EntityVillager['村民'/64, l='MpServer', x=-281.69, y=4.00, z=-1288.28], EntityVillager['村民'/65, l='MpServer', x=-279.50, y=4.00, z=-1284.00], EntityVillager['村民'/66, l='MpServer', x=-283.66, y=4.00, z=-1288.50], EntityVillager['村民'/68, l='MpServer', x=-275.72, y=5.00, z=-1277.13], EntityVillager['村民'/69, l='MpServer', x=-275.78, y=5.00, z=-1276.09], EntityItemFrame['entity.ItemFrame.name'/73, l='MpServer', x=-256.50, y=9.50, z=-1321.06], EntityItemFrame['entity.ItemFrame.name'/74, l='MpServer', x=-257.50, y=9.50, z=-1321.06], EntityPainting['画'/75, l='MpServer', x=-256.50, y=9.50, z=-1325.94], EntityBat['蝙蝠'/76, l='MpServer', x=-264.69, y=6.10, z=-1312.78], EntityBat['蝙蝠'/77, l='MpServer', x=-259.81, y=5.10, z=-1313.25], EntityVillager['村民'/78, l='MpServer', x=-258.30, y=5.00, z=-1301.30], EntityVillager['村民'/79, l='MpServer', x=-259.43, y=5.00, z=-1301.39], EntityVillager['村民'/80, l='MpServer', x=-258.41, y=5.00, z=-1302.29], EntityBat['蝙蝠'/81, l='MpServer', x=-259.81, y=5.10, z=-1310.25], EntityBat['蝙蝠'/82, l='MpServer', x=-259.81, y=5.10, z=-1310.44], EntityVillager['村民'/83, l='MpServer', x=-276.66, y=6.00, z=-1301.50], EntityVillager['村民'/84, l='MpServer', x=-276.69, y=5.00, z=-1305.50], EntityVillager['村民'/85, l='MpServer', x=-264.50, y=5.00, z=-1311.72], EntityVillager['村民'/86, l='MpServer', x=-275.59, y=5.00, z=-1301.63], EntityBat['蝙蝠'/88, l='MpServer', x=-257.75, y=6.10, z=-1277.25], EntityItemFrame['entity.ItemFrame.name'/101, l='MpServer', x=-255.50, y=9.50, z=-1321.06], EntityBat['蝙蝠'/102, l='MpServer', x=-245.75, y=7.10, z=-1314.75], EntityBat['蝙蝠'/103, l='MpServer', x=-245.75, y=7.10, z=-1310.25], EntityVillager['村民'/104, l='MpServer', x=-256.97, y=4.00, z=-1291.75], EntityVillager['村民'/105, l='MpServer', x=-255.13, y=4.00, z=-1290.31], EntityBat['蝙蝠'/106, l='MpServer', x=-253.19, y=6.00, z=-1278.25], EntityVillager['村民'/107, l='MpServer', x=-256.34, y=4.00, z=-1290.47], EntityBat['蝙蝠'/108, l='MpServer', x=-251.88, y=4.00, z=-1276.00], EntityBat['蝙蝠'/118, l='MpServer', x=-205.25, y=4.00, z=-1295.22]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394)
    at org.multimc.EntryPoint.listen(EntryPoint.java:170)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_51, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 269823640 bytes (257 MB) / 1060634624 bytes (1011 MB) up to 1060634624 bytes (1011 MB)
    JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx1024m
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 Optifine OptiFine_1.7.10_HD_U_C1 125 mods loaded, 125 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAA   mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAA   FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHIJAAAA   Forge{10.13.4.1448} [Minecraft Forge](forge-1.7.10-10.13.4.1448-1.7.10-universal.jar) 
    UCHIJAAAA   Aroma1997Core{1.0.2.14} [Aroma1997Core]([A]Aroma1997Core-1.7.10-1.0.2.14.jar) 
    UCHIJAAAA   CodeChickenCore{1.0.7.46} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAA   appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core](minecraft.jar) 
    UCHIJAAAA   InputFix{1.7.10-v5} [InputFix](minecraft.jar) 
    UCHIJAAAA   NotEnoughItems{1.0.5.111} [Not Enough Items]([NEI]NotEnoughItems-1.7.10-1.0.5.111-universal.jar) 
    UCHIJAAAA   ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) 
    UCHIJAAAA   WitchingGadgetsCore{1.1.9} [Witching Gadgets Core](minecraft.jar) 
    UCHIJAAAA   OpenModsCore{0.7.3} [OpenModsCore](minecraft.jar) 
    UCHIJAAAA   debug{1.0} [debug]([WG]denseores-1.6.2.jar) 
    UCHIJAAAA   AppleCore{1.1.0} [AppleCore]([A]AppleCore-mc1.7.10-1.1.0.jar) 
    UCHIJAAAA   Aroma1997CoreHelper{1.0.2.14} [Aroma1997Core|Helper]([A]Aroma1997Core-1.7.10-1.0.2.14.jar) 
    UCHIJAAAA   IC2{2.2.757-experimental} [IndustrialCraft 2]([IC2]industrialcraft-2-2.2.757-experimental.jar) 
    UCHIJAAAA   ImmibisCore{59.1.1} [Immibis Core]([A]immibis-core-59.1.1.jar) 
    UCHIJAAAA   Mantle{1.7.10-0.3.2.jenkins184} [Mantle]([A]Mantle-1.7.10-0.3.2.jar) 
    UCHIJAAAA   OpenMods{0.7.3} [OpenMods]([A]OpenModsLib-1.7.10-0.7.3.jar) 
    UCHIJAAAA   Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) 
    UCHIJAAAA   TravellersGear{1.16.4} [Traveller's Gear]([A]TravellersGear-1.7.10-1.16.4.jar) 
    UCHIJAAAA   appliedenergistics2{rv2-stable-10} [Applied Energistics 2]([AE]appliedenergistics2-rv2-stable-10.jar) 
    UCHIJAAAA   Waila{1.5.10} [Waila]([NEI]Waila-1.5.10_1.7.10.jar) 
    UCHIJAAAA   extracells{2.2.73} [Extra Cells 2]([AE]ExtraCells-1.7.10-2.2.73b129.jar) 
    UCHIJAAAA   hud{1.1a} [Better HUD]([F]Better HUD by NukeDuck [1.7.10][1.1a].zip) 
    UCHIJAAAA   FastCraft{1.21} [FastCraft]([F]fastcraft-1.21.jar) 
    UCHIJAAAA   inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks]([F]InventoryTweaks-1.59-dev-152.jar) 
    UCHIJAAAA   journeymap{5.0.1} [JourneyMap]([F]JourneyMap5.0.1_FairPlay_MC1.7.10.jar) 
    UCHIJAAAA   MineTweaker3{3.0.9B} [MineTweaker 3]([F]MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHIJAAAA   modtweaker2{0.9.1} [Mod Tweaker 2]([F]ModTweaker~2-0.9.1.jar) 
    UCHIJAAAA   MouseTweaks{2.4.4} [Mouse Tweaks]([F]MouseTweaks-2.4.4-mc1.7.10.jar) 
    UCHIJAAAA   Progression{0.4.1} [Progression]([F]Progression-1.7.10-0.4.1.jar) 
    UCHIJAAAA   SpiceOfLife{1.2.3} [The Spice of Life]([F]SpiceOfLife-mc1.7.10-1.2.3.jar) 
    UCHIJAAAA   UnicodeFontFixer{1.1.2} [UnicodeFontFixer]([F]UnicodeFontFixer-1.1.2-mc1.7.10.jar) 
    UCHIJAAAA   AdvancedRepulsionSystems{59.0.3} [Advanced Repulsion Systems]([IC2]adv-repulsion-systems-59.0.3.jar) 
    UCHIJAAAA   AdvancedMachines{59.0.2} [Advanced Machines]([IC2]advanced-machines-59.0.2.jar) 
    UCHIJAAAA   AdvancedSolarPanel{1.7.10-3.5.1} [Advanced Solar Panels]([IC2]AdvancedSolarPanel-1.7.10-3.5.1.jar) 
    UCHIJAAAA   AFSU{1.2.1a-Mustard} [AFSU Mod]([IC2]AFSU-1.2.1a-Mustard.jar) 
    UCHIJAAAA   CompactSolars{4.4.39.315} [Compact Solar Arrays]([IC2]CompactSolars-1.7.10-4.4.39.315-universal.jar) 
    UCHIJAAAA   BuildCraft|Core{7.0.17} [BuildCraft](buildcraft-7.0.17.jar) 
    UCHIJAAAA   GraviSuite{1.7.10-2.0.3} [Graviation Suite]([IC2]GraviSuite-1.7.10-2.0.3.jar) 
    UCHIJAAAA   IC2NuclearControl{2.2.5a-GoingForTheKill} [Nuclear Control 2]([IC2]IC2NuclearControl-2.2.5a-GoingForTheKill.jar) 
    UCHIJAAAA   Uncomplication{0.1.0.1} [Uncomplication]([IC2]Uncomplication-1.7.10-0.1.0.1.jar) 
    UCHIJAAAA   NEIAddons{1.12.10.33} [NEI Addons]([NEI]neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|AppEng{1.12.10.33} [NEI Addons: Applied Energistics 2]([NEI]neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   Natura{2.2.0} [Natura]([WG]natura-1.7.10-2.2.0.1.jar) 
    UCHIJAAAA   Forestry{3.6.3.20} [Forestry for Minecraft]([RF]forestry_1.7.10-3.6.3.20.jar) 
    UCHIJAAAA   BinnieCore{2.0-pre14} [Binnie Core]([RF]binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   Botany{2.0-pre14} [Botany]([RF]binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   NEIAddons|Botany{1.12.10.33} [NEI Addons: Botany]([NEI]neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|Forestry{1.12.10.33} [NEI Addons: Forestry]([NEI]neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|CraftingTables{1.12.10.33} [NEI Addons: Crafting Tables]([NEI]neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   NEIAddons|ExNihilo{1.12.10.33} [NEI Addons: Ex Nihilo]([NEI]neiaddons-1.12.10.33-mc1.7.10.jar) 
    UCHIJAAAA   neiintegration{1.0.11} [NEI Integration]([NEI]NEIIntegration-MC1.7.10-1.0.11.jar) 
    UCHIJAAAA   TConstruct{1.7.10-1.8.5.build957} [Tinkers' Construct]([TiC]TConstruct-1.7.10-1.8.5.jar) 
    UCHIJAAAA   ForgeMultipart{1.2.0.345} [Forge Multipart](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ExtraUtilities{1.2.8} [Extra Utilities]([RF]extrautilities-1.2.8.jar) 
    UCHIJAAAA   Thaumcraft{4.2.3.5} [Thaumcraft]([TC]Thaumcraft-1.7.10-4.2.3.5.jar) 
    UCHIJAAAA   harvestcraft{1.7.10j} [Pam's HarvestCraft]([WG]Pam's HarvestCraft 1.7.10j.jar) 
    UCHIJAAAA   ExtraTiC{1.4.5} [ExtraTiC]([TiC]ExtraTiC-1.7.10-1.4.5.jar) 
    UCHIJAAAA   WailaHarvestability{1.1.2} [Waila Harvestability]([NEI]WailaHarvestability-mc1.7.x-1.1.2.jar) 
    UCHIJAAAA   BiblioCraft{1.10.4} [BiblioCraft]([O]BiblioCraft[v1.10.4][MC1.7.10].jar) 
    UCHIJAAAA   BiblioWoodsForestry{1.7} [BiblioWoods Forestry Edition]([O]BiblioWoods[Forestry][v1.7].jar) 
    UCHIJAAAA   BiblioWoodsNatura{1.5} [BiblioWoods Natura Edition]([O]BiblioWoods[Natura][v1.5].jar) 
    UCHIJAAAA   ChickenChunks{1.3.4.19} [ChickenChunks]([O]ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
    UCHIJAAAA   EnderStorage{1.4.7.36} [EnderStorage]([O]EnderStorage-1.7.10-1.4.7.36-universal.jar) 
    UCHIJAAAA   IronChest{6.0.62.742} [Iron Chest]([O]ironchest-1.7.10-6.0.62.742-universal.jar) 
    UCHIJAAAA   JABBA{1.2.1} [JABBA]([O]Jabba-1.2.1a_1.7.10.jar) 
    UCHIJAAAA   OpenBlocks{1.4.3} [OpenBlocks]([O]OpenBlocks-1.7.10-1.4.3.jar) 
    UCHIJAAAA   RIO{2.3} [RemoteIO]([O]RemoteIO-1.7.10-2.3.B0-universal.jar) 
    UCHIJAAAA   StorageDrawers{1.7.10-1.5.12} [Storage Drawers]([O]StorageDrawers-1.7.10-1.5.12.jar) 
    UCHIJAAAA   StorageDrawersForestry{1.7.10-1.0.1} [Storage Drawers: Forestry Pack]([O]StorageDrawers-Forestry-1.7.10-1.0.1.jar) 
    UCHIJAAAA   StorageDrawersNatura{1.7.10-1.0.2} [Storage Drawers: Natura Pack]([O]StorageDrawers-Natura-1.7.10-1.0.2.jar) 
    UCHIJAAAA   Translocator{1.1.2.15} [Translocator]([O]Translocator-1.7.10-1.1.2.15-universal.jar) 
    UCHIJAAAA   warpbook{2.0.null} [Warp Book]([O]warpbook-1.7.10_2.0.36.jar) 
    UCHIJAAAA   WR-CBE|Core{1.4.1.9} [WR-CBE Core]([O]WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Addons{1.4.1.9} [WR-CBE Addons]([O]WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   WR-CBE|Logic{1.4.1.9} [WR-CBE Logic]([O]WR-CBE-1.7.10-1.4.1.9-universal.jar) 
    UCHIJAAAA   MrTJPCoreMod{1.1.0.30} [MrTJPCore](MrTJPCore-1.1.0.30-universal.jar) 
    UCHIJAAAA   ProjRed|Core{4.7.0pre7.91} [ProjectRed Core]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Base.jar) 
    UCHIJAAAA   ProjRed|Transmission{4.7.0pre7.91} [ProjectRed Transmission]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Integration.jar) 
    UCHIJAAAA   ProjRed|Transportation{4.7.0pre7.91} [ProjectRed Transportation]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Mechanical.jar) 
    UCHIJAAAA   ProjRed|Exploration{4.7.0pre7.91} [ProjectRed Exploration]([PR]ProjectRed-1.7.10-4.7.0pre7.91-World.jar) 
    UCHIJAAAA   ProjRed|Compatibility{4.7.0pre7.91} [ProjectRed Compatibility]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Compat.jar) 
    UCHIJAAAA   ProjRed|Integration{4.7.0pre7.91} [ProjectRed Integration]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Integration.jar) 
    UCHIJAAAA   ProjRed|Fabrication{4.7.0pre7.91} [ProjectRed Fabrication]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Fabrication.jar) 
    UCHIJAAAA   ProjRed|Illumination{4.7.0pre7.91} [ProjectRed Illumination]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Lighting.jar) 
    UCHIJAAAA   ProjRed|Expansion{4.7.0pre7.91} [ProjectRed Expansion]([PR]ProjectRed-1.7.10-4.7.0pre7.91-Mechanical.jar) 
    UCHIJAAAA   ExtraBees{2.0-pre14} [Extra Bees]([RF]binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   ExtraTrees{2.0-pre14} [Extra Trees]([RF]binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   Genetics{2.0-pre14} [Genetics]([RF]binnie-mods-2.0-pre14.jar) 
    UCHIJAAAA   EnderIO{1.7.10-2.2.8.381} [Ender IO]([RF]EnderIO-1.7.10-2.2.8.381.jar) 
    UCHIJAAAA   BuildCraft|Silicon{7.0.17} [BC Silicon](buildcraft-7.0.17.jar) 
    UCHIJAAAA   BuildCraft|Transport{7.0.17} [BC Transport](buildcraft-7.0.17.jar) 
    UCHIJAAAA   LogisticsPipes{0.9.2.22} [Logistics Pipes]([RF]logisticspipes-0.9.2.22.jar) 
    UCHIJAAAA   BuildCraft|Factory{7.0.17} [BC Factory](buildcraft-7.0.17.jar) 
    UCHIJAAAA   BuildCraft|Energy{7.0.17} [BC Energy](buildcraft-7.0.17.jar) 
    UCHIJAAAA   BuildCraft|Builders{7.0.17} [BC Builders](buildcraft-7.0.17.jar) 
    UCHIJAAAA   Railcraft{9.6.1.0} [Railcraft]([RF]Railcraft_1.7.10-9.6.1.0.jar) 
    UCHIJAAAA   Automagy{0.26.3} [Automagy]([TC]Automagy-1.7.10-0.26.3.jar) 
    UCHIJAAAA   EMT{2.0.0Alpha4} [Electro-Magic Tools]([TC]ElectroMagicTools-1.7.10-2.0.0-CUSTOM_V4.1.jar) 
    UCHIJAAAA   ThaumicTinkerer{unspecified} [Thaumic Tinkerer]([TC]ThaumicTinkerer-2.5-1.7.10-507.jar) 
    UCHIJAAAA   ForbiddenMagic{1.7.10-0.57} [Forbidden Magic]([TC]Forbidden Magic-1.7.10-0.57.jar) 
    UCHIJAAAA   MagicBees{1.7.10-2.3.3} [Magic Bees]([TC]magicbees-1.7.10-2.3.3.jar) 
    UCHIJAAAA   tcnodetracker{1.1.2} [TC Node Tracker]([TC]tcnodetracker-1.7.10-1.1.2.jar) 
    UCHIJAAAA   thaumcraftgates{1.4.1} [Thaumcraft Gates]([TC]ThaumcraftGates-1.4.1.jar) 
    UCHIJAAAA   ThaumcraftMobAspects{1.7.2-2A} [Thaumcraft Mob Aspects]([TC]ThaumcraftMobAspects-1.7.2-2A.jar) 
    UCHIJAAAA   thaumcraftneiplugin{@VERSION@} [Thaumcraft NEI Plugin]([TC]thaumcraftneiplugin-1.7.10-1.7a.jar) 
    UCHIJAAAA   thaumicenergistics{0.8.10.8} [Thaumic Energistics]([TC]thaumicenergistics-0.8.10.8.jar) 
    UCHIJAAAA   ThaumicHorizons{1.1.5} [Thaumic Horizons]([TC]thaumichorizons-1.7.10-1.1.6.jar) 
    UCHIJAAAA   TwilightForest{2.3.7} [The Twilight Forest]([WG]twilightforest-1.7.10-2.3.7.jar) 
    UCHIJAAAA   WitchingGadgets{1.1.9} [Witching Gadgets]([TC]WitchingGadgets-1.7.10-1.1.9.jar) 
    UCHIJAAAA   TiCTooltips{1.2.5} [TiC Tooltips]([TiC]TiCTooltips-mc1.7.10-1.2.5.jar) 
    UCHIJAAAA   TMechworks{0.2.14.100} [Tinkers' Mechworks]([TiC]TMechworks-1.7.10-0.2.14.100.jar) 
    UCHIJAAAA   EnderZoo{1.7.10-1.0.11.28} [Ender Zoo]([WG]EnderZoo-1.7.10-1.0.11.28.jar) 
    UCHIJAAAA   harvestthenether{1.7.10} [Pam's Harvest the Nether]([WG]Pam's Harvest the Nether 1.7.10a.jar) 
    UCHIJAAAA   weeeflowers{1.7.2b} [Pam's Weee! Flowers]([WG]Pam's WeeeFlowers 1.7.2b.zip) 
    UCHIJAAAA   BuildCraft|Robotics{7.0.17} [BC Robotics](buildcraft-7.0.17.jar) 
    UCHIJAAAA   McMultipart{1.2.0.345} [Minecraft Multipart Plugin](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    UCHIJAAAA   ForgeRelocation{0.0.1.3} [ForgeRelocation](ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
    UCHIJAAAA   MCFrames{1.0} [MCFrames](ForgeRelocation-1.7.10-0.0.1.3-universal.jar) 
    UCHIJAAAA   RelocationFMP{0.0.1.2} [RelocationFMP](ForgeRelocationFMP-1.7.10-0.0.1.2-universal.jar) 
    UCHIJAAAA   HungerOverhaul{1.7.10-1.0.0.jenkins75} [Hunger Overhaul]([F]HungerOverhaul-1.7.10-1.0.0.jar) 
    UCHIJAAAA   IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks]([TiC]IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
    UCHIJAAAA   denseores{1.0} [Dense Ores]([WG]denseores-1.6.2.jar) 
    UCHIJAAAA   ForgeMicroblock{1.2.0.345} [Forge Microblocks](ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
    GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 353.06' Renderer: 'GeForce GTX 750/PCIe/SSE2'
    OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
    Class transformer null safety: all safe
    Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
    AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
    TConstruct Environment: Environment healthy.
    Stencil buffer state: Function set: GL30, pool: internal, bits: 8
    Forestry : Warning: You have mods that change the behavior of Minecraft, ForgeModLoader, and/or Minecraft Forge to your client: 
Optifine
These may have caused this error, and may not be supported. Try reproducing the crash WITHOUT these mods, and report it then.
    AE2 Integration: IC2:ON, RotaryCraft:OFF, RC:ON, BC:ON, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
    Launched Version: MultiMC5
    LWJGL: 2.9.1
    OpenGL: GeForce GTX 750/PCIe/SSE2 GL version 4.5.0 NVIDIA 353.06, NVIDIA Corporation
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: 简体中文 (中国)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by joshiejack** [comment]
With the way I have rewritten the treeeditor should be fixed in 1.8.9. Sorry not for 1.7.10 but i'm done there, I have a lot of mods to work on and i'd rather get them all updated >.>
