### ISSUE TITLE
A Suggestion about adding an "infinite" option

### ISSUE THREAD

**Issue by Nullga** [joshiejack/Progression#32]
Hi, I'm loving in your mod a lot on my server not only for tweaking but as a subsidiary to some functions  that is lacking by default in the other mods.
However would it be possible to have an option "infinite" in the repeatable section by any chance?
It anyway comes to be realized with setting the number to one billion times though I still feel better if an infinite option is available. I appreciate if you don't mind to consider it. Thanks!

**Comment by joshiejack** [comment]
Infinite is added in the 1.8.9 version :)
