### ISSUE TITLE
Removing items!

### ISSUE THREAD

**Issue by Dominance** [joshiejack/Progression#33]
So if a player removes a mod and it had progression set to prevent crafting. The items revert to a furnace automatically. This basically ensures that nothing at all can be removed. Some servers for instance will remove chunk loaders or mods entirely. Such as mystcraft being a good example. My solution make a basic item with no use at all to revert this state to and not a furnace. If you cannot place or use a furnace you block all progression.

**Comment by Dominance** [comment]
Thanks a ton joshie. Are you updating this for 1.8.9 by any chance?

**Comment by joshiejack** [comment]
Yep that's what i'm working on. I wasn't sure about this one, so I just closed it. I don't really want to add a special block for these cases. I could make the items default to like bedrock and a useless item from my mod. But I didn't really like the idea of that. What i'd actually be happier doing is removing the criteria altogether if it was something that no longer exists.

**Comment by Dominance** [comment]
Yeah it's just been a pain to work with on my part with over 10k items linked to progression every pack update breaks the json. So bedrock would be a great alternative block.
