### ISSUE TITLE
Crash when opening edited progression GUI

### ISSUE THREAD

**Issue by Freddo3000** [joshiejack/Progression#34]
After I had largely edited the progression config in-game, in singleplayer, after restarting the modpack and trying to open the GUI again it immediately closes down minecraft. Something that I also noticed is that it also leaves the process still running in the background. 

I run with this modpack on the technic launcher: http://www.technicpack.net/modpack/mcdestiny-20.720894

I have tested putting it on a server, worked without a problem. Though as soon as a client tries to open the gui on the server, the client crashes.

I run Windows 10, with Java 8 and forge version 1448. I have a more than enough powerful computer to run things like this.

[You can get the logs and criteria.json files from here.](https://www.dropbox.com/s/oxtywnlw5kpqc27/Errors.zip?dl=0)

If you could fix and/or tell me what is causing it to crash, it would be very much appreciated. But until then, I'm going to drop progression.

**Comment by joshiejack** [comment]
Yeah progression was very unstable in 1.7.10, for me it was a very experimental mod, I've learnt a few things from it, and am working on improving things in the 1.8.9 version.
