### ISSUE TITLE
Client disconnect/No deathdrops

### ISSUE THREAD

**Issue by felixkraas** [joshiejack/Progression#35]
Hi,
we are having problems with killing each other. When you kill someone (PvP) you are disconnected from the server. On the screen is then displayed "internal server error". Killed one however doesn't drop it's inventory. For us it sadly seems like your mod is causing the trouble here. Correct me if I am wrong with that.
Here is the stacktrace:
http://pastebin.com/nRZ91TPB

Just ask if you need a modlist.

**Comment by joshiejack** [comment]
Looks like it had to do with not being able to find the string name of the entity. Shall fix for the 1.8.9 version.
