### ISSUE TITLE
[Suggestion] Add a dynamic %player variable for command

### ISSUE THREAD

**Issue by TerdyTheTerd** [joshiejack/Progression#36]
I was wondering if it would be possible to add some type of variable for the command result, so say you could have a reward for completing an action be "nick %player Hero" and that would set whoever completed the action to have their nickname changed. Currently I don't see anyway to specify for a command to be run for the current player, and this would be extremely useful IMO

**Comment by joshiejack** [comment]
Technically that was already doable, it just wasn't documented. You could type @u and it would apply to the player that the command was being awarded to. In my 1.8.9 version I'll probably try to include a book to explain some basic things that people might not know like that.
