### ISSUE TITLE
Not saving

### ISSUE THREAD

**Issue by fishmealx** [joshiejack/Progression#37]
I made a set of criteria, and after some number of server restarts it was gone. I made another, and it was gone as soon as I backed out of it. If I make a bunch of blank tabs and exit, they are there when I return, but if I click a tab to edit it, then back out, it's a blank slate.

**Comment by joshiejack** [comment]
I noticed when updating to 1.8.9 that the saving system can be really buggy and not save like half the time :/. I've rewritten it, and from what I can tlel it's a bit more stable/robust so in the future should hopefully work better on future versions.
