### ISSUE TITLE
Crash when crafting certain items

### ISSUE THREAD

**Issue by TerdyTheTerd** [joshiejack/Progression#38]
I believe this is actually a conflict between progression and any number of other mods, It seems that random items, typically ones with gold ingots or diamonds, crash random players while crafting with them, a few examples are some players crash when crafting a gold block, others crash when crafting a golden chest, some crash when crafting a gold inlay and some players don't crash at all. At the time there are no criteria set on either client or server (it was a planned release thing for the classes). Here is one crash report that a player provided me with, it looks like progression is checking when the obtains an item(crafting it) and either conflicts with NEI or some other mod, or iteself. http://pastebin.com/7aynH6Bx Any help would be appreciated and I would gladly donate if this could somehow be fixed.

**Comment by joshiejack** [comment]
Sorry that I pretty much abandoned everything I'm back now, and working on the 1.8.9 version. The 1.7 version was pretty unstable from what I can tell. Looks like the crash was related to not being able to find the item for certain blocks, which is weird as they should have an item.
