### ISSUE TITLE
Add support for other mods custom crafting stations

### ISSUE THREAD

**Issue by Anghelos92** [joshiejack/Progression#40]
Can you add support tu Applied energistics and ancient warfare 2 stations? Or could you add a config file where we can add the IDs of the custom crafting stations we want to obey to progression rules? Thank you and good job :)

**Comment by joshiejack** [comment]
Technically the former should be working in the 1.7.10 version. Blocking them from following the rules is a lot more work than a config would allow, but I plan to improve upon the limited support and do as much as I can in the 1.8.9 version.
