### ISSUE TITLE
Flavor text enhancement.

### ISSUE THREAD

**Issue by mindcloud69** [joshiejack/Progression#42]
I would like to see the ability to add flavor text to any element of the mod to enhance the user friendliness and story telling aspect of this mod.

**Comment by joshiejack** [comment]
Text like this wouldn't be added directly to progression as it's goal is to be more of a behind the scenes running tool. I have integration with Enchiridion in the works, which would let you display progression data, rewards, perform actions and other things, as well as write the usual text.
