### ISSUE TITLE
How to reset progression for one player only?

### ISSUE THREAD

**Issue by Kerydwenn** [joshiejack/Progression#44]
We need to reset progression for one player. How can we do that?

Due to a bug in our current modpack (Divergence), unlocking one of the mods didn't have any effect. We found a fix to correct the bug itself, however now only players who hadn't unlocked that research before the fix can unlock the formerly problematic mod. The players who had unlocked it before the fix can't, and this is why we need to reset their progression.

Our admin hasn't found a command to do that. (We tried changing the character's name on Mojang's site, but the ID assigned to the renamed character was the same, so our admin couldn't change anything.)

**Comment by joshiejack** [comment]
I know this is late... But I'm just getting back in to modding/progression now. The only way i can think in the 1.7 version is to edit the progression data with a nbt editor. I'll add a player specific command for future versions.
