### ISSUE TITLE
conflicting

### ISSUE THREAD

**Issue by SvEgiiVEteR** [joshiejack/Progression#50]
conflict with 4 mods
buildcraft-compat-7.1.5.jar
autopackager-1.5.9a.jar
immibis-microblocks-59.1.2.jar
Progression-1.7.10-0.4.1.jar
https://gist.github.com/fcebb505f98311b3e495e3bf80a4147e

**Comment by joshiejack** [comment]
1.7.10 is no longer supported. I'm going to assume a newer version of autopackager meant the asm i was doing to get it to comply to my rules broke. Honestly the 1.7.10 version of progression was experimental and full of many issues that it's not really recommended to use.

**Comment by SvEgiiVEteR** [comment]
very bad..

**Comment by SvEgiiVEteR** [comment]
very bad.. ((

**Comment by joshiejack** [comment]
I'm sorry but i just do not have the time. I have a bunch of other things i need to work on. 1.7.10 is two versions behind, sure it's good for players. But it's not a good use of my time working on an old version when not all my mods are on the latest as is.

**Comment by immibis** [comment]
Immibis's Microblocks is likely not causing the crash, except insofar as its presence causes Buildcraft Compat to load the Immibis's Microblocks compatibility module.
