### ISSUE TITLE
Inquiry

### ISSUE THREAD

**Issue by Omuck3** [joshiejack/Progression#51]
Hello. I was just wondering if there's any plans to add the features from the current 1.8.9 version into a 1.7.10 version.  While I could try to update the pack to 1.8, a lot of mods would have to be removed.  The pack is still in the early alpha stages, so I'm trying to get any issues sorted out early.

Thanks for any info! :)

**Comment by joshiejack** [comment]
Even If I wanted to, I don't have time to do it, have other projects taking up all my free time.

**Comment by Omuck3** [comment]
Ok, I love the mod by the way! :)
