### ISSUE TITLE
1.9 :( 

### ISSUE THREAD

**Issue by RebeccaRedstone** [joshiejack/Progression#59]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  ProgressionTransformer (Progression-1.9-0.5.2.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.59-universal.jar)
  LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.5.jar)
  CCLCorePlugin (CodeChickenLib-1.9-2.0.1.29-universal.jar)
  LoadingPlugin (Quark-beta-18.jar)
  Player Stats Core (PlayerStats_1.9-1.1.0.jar)
  CCCDeobfPlugin (unknown)
  ShetiPhian-ASM (shetiphiancore-1.9.0-3.2.5.jar)
  BetterFoliageLoader (BetterFoliage-MC1.9-2.0.11.jar)
  MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  DLFMLCorePlugin (DynamicLights-1.9.jar)
Contact their authors BEFORE contacting forge

// Uh... Did I do that?

Time: 14/06/16 8:12 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at joshie.progression.criteria.filters.item.FilterItemStack.matches(FilterItemStack.java:35)
    at joshie.progression.criteria.filters.item.FilterBaseItem.matches(FilterBaseItem.java:34)
    at joshie.progression.gui.filters.FeatureItemPreview.updateSearch(FeatureItemPreview.java:65)
    at joshie.progression.gui.editors.FeatureDrawable.drawingMouseClicked(FeatureDrawable.java:224)
    at joshie.progression.gui.editors.FeatureDrawable.mouseClicked(FeatureDrawable.java:265)
    at joshie.progression.gui.core.GuiCore.func_73864_a(GuiCore.java:159)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
    at joshie.progression.gui.core.GuiCore.func_146274_d(GuiCore.java:244)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1694)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1051)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:366)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at joshie.progression.criteria.filters.item.FilterItemStack.matches(FilterItemStack.java:35)
    at joshie.progression.criteria.filters.item.FilterBaseItem.matches(FilterBaseItem.java:34)
    at joshie.progression.gui.filters.FeatureItemPreview.updateSearch(FeatureItemPreview.java:65)
    at joshie.progression.gui.editors.FeatureDrawable.drawingMouseClicked(FeatureDrawable.java:224)
    at joshie.progression.gui.editors.FeatureDrawable.mouseClicked(FeatureDrawable.java:265)
    at joshie.progression.gui.core.GuiCore.func_73864_a(GuiCore.java:159)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:540)
    at joshie.progression.gui.core.GuiCore.func_146274_d(GuiCore.java:244)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:509)

-- Affected screen --
Details:
    Screen name: joshie.progression.gui.core.GuiCore

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityPlayerSP['RebeccaRedstone'/279929, l='MpServer', x=1545.47, y=60.00, z=758.51]]
    Chunk stats: MultiplayerChunkCache: 441, 441
    Level seed: 0
    Level generator: ID 06 - BIOMESOP, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (1509,63,670), Chunk: (at 5,3,14 in 94,41; contains blocks 1504,0,656 to 1519,255,671), Region: (2,1; contains chunks 64,32 to 95,63, blocks 1024,0,512 to 1535,255,1023)
    Level time: 5155962 game time, 4874890 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
    Forced entities: 84 total; [EntityPlayerSP['RebeccaRedstone'/279929, l='MpServer', x=1535.70, y=64.00, z=749.30], EntitySquid['Squid'/395790, l='MpServer', x=1544.40, y=62.14, z=820.60], EntityZombie['Zombie'/396055, l='MpServer', x=1488.50, y=37.00, z=804.50], EntityItem['item.item.terraqueous.multifood.plum'/388893, l='MpServer', x=1559.31, y=65.00, z=731.42], EntityItem['item.item.terraqueous.itemmain.leather.belt'/388377, l='MpServer', x=1567.52, y=65.00, z=702.83], EntityItem['item.item.terraqueous.itemmain.leather.boot1'/388376, l='MpServer', x=1567.68, y=65.00, z=702.78], EntityChickenBike['entity.animalbikes.ChickenBike.name'/335643, l='MpServer', x=1544.50, y=65.94, z=749.50], EntitySkeleton['Skeleton'/396056, l='MpServer', x=1492.50, y=37.00, z=801.50], EntityPlayerSP['RebeccaRedstone'/279929, l='MpServer', x=1545.47, y=60.00, z=758.51], EntityItem['item.item.terraqueous.multifood.plum'/386084, l='MpServer', x=1572.68, y=65.00, z=744.87], EntityItem['item.item.terraqueous.multifood.plum'/381731, l='MpServer', x=1578.88, y=66.00, z=759.06], EntityItem['item.item.terraqueous.multifood.plum'/386094, l='MpServer', x=1554.61, y=66.00, z=747.36], EntityBabySquid['Baby Squid'/390442, l='MpServer', x=1602.98, y=60.00, z=802.30], EntityCow['Cow'/82228, l='MpServer', x=1511.55, y=63.00, z=798.81], EntityItem['item.item.terraqueous.multifood.plum'/387888, l='MpServer', x=1562.39, y=66.00, z=767.57], EntityCreeper['Creeper'/395326, l='MpServer', x=1616.50, y=19.00, z=815.50], EntityItem['item.item.dyePowder.black'/393787, l='MpServer', x=1602.47, y=60.00, z=801.50], EntityPlayerSP['RebeccaRedstone'/279929, l='MpServer', x=1543.00, y=66.00, z=750.28], EntityBat['Bat'/392525, l='MpServer', x=1594.42, y=26.07, z=702.33], EntityZombie['Zombie'/395085, l='MpServer', x=1587.43, y=25.00, z=686.70], EntityCow['Cow'/79, l='MpServer', x=1467.85, y=67.00, z=764.27], EntityCow['Cow'/80, l='MpServer', x=1469.21, y=67.00, z=777.08], EntitySkeleton['Skeleton'/393041, l='MpServer', x=1611.50, y=13.00, z=834.50], EntityCow['Cow'/85, l='MpServer', x=1490.22, y=66.00, z=723.42], EntityCow['Cow'/87, l='MpServer', x=1477.55, y=65.00, z=748.15], EntityCow['Cow'/90, l='MpServer', x=1482.73, y=66.00, z=790.89], EntityItem['item.item.terraqueous.multifood.plum'/392799, l='MpServer', x=1568.88, y=66.00, z=766.52], EntityCow['Cow'/91, l='MpServer', x=1484.94, y=66.00, z=791.48], EntityCow['Cow'/92, l='MpServer', x=1487.44, y=65.00, z=796.25], EntityCow['Cow'/95, l='MpServer', x=1488.30, y=67.00, z=698.49], EntityCow['Cow'/96, l='MpServer', x=1502.77, y=67.00, z=694.36], EntityCow['Cow'/97, l='MpServer', x=1504.17, y=64.32, z=691.88], EntityCow['Cow'/99, l='MpServer', x=1486.70, y=66.00, z=789.16], EntityCow['Cow'/100, l='MpServer', x=1490.76, y=65.00, z=785.31], EntityCreeper['Creeper'/396643, l='MpServer', x=1618.50, y=20.00, z=817.50], EntityCow['Cow'/107, l='MpServer', x=1522.66, y=66.00, z=687.63], EntityCow['Cow'/108, l='MpServer', x=1558.23, y=64.00, z=714.51], EntityCow['Cow'/109, l='MpServer', x=1535.37, y=68.00, z=689.82], EntityCow['Cow'/110, l='MpServer', x=1536.22, y=66.00, z=699.52], EntityCow['Cow'/111, l='MpServer', x=1517.91, y=66.00, z=698.64], EntityCow['Cow'/112, l='MpServer', x=1521.60, y=64.00, z=792.21], EntityCow['Cow'/132, l='MpServer', x=1543.47, y=63.00, z=798.22], EntityItem['item.item.terraqueous.multifood.plum'/387459, l='MpServer', x=1550.06, y=66.00, z=738.57], EntityBat['Bat'/394380, l='MpServer', x=1620.43, y=14.46, z=836.47], EntityItem['item.item.terraqueous.multifood.plum'/392590, l='MpServer', x=1558.99, y=65.00, z=734.87], EntitySkeleton['Skeleton'/395401, l='MpServer', x=1594.50, y=25.00, z=690.50], EntityPlayerSP['RebeccaRedstone'/279929, l='MpServer', x=1541.52, y=65.00, z=747.01], EntitySheep['Sheep'/151, l='MpServer', x=1549.45, y=64.00, z=680.45], EntityCow['Cow'/153, l='MpServer', x=1563.51, y=65.00, z=693.83], EntityCow['Cow'/279965, l='MpServer', x=1543.73, y=62.48, z=819.47], EntitySkeleton['Skeleton'/394909, l='MpServer', x=1524.50, y=12.00, z=738.50], EntityChickenBike['entity.animalbikes.ChickenBike.name'/153759, l='MpServer', x=1548.50, y=60.88, z=762.50], EntityCow['Cow'/279963, l='MpServer', x=1533.09, y=62.48, z=807.09], EntityCow['Cow'/279972, l='MpServer', x=1514.81, y=66.00, z=834.74], EntityCow['Cow'/279975, l='MpServer', x=1496.81, y=66.00, z=833.56], EntityCreeper['Creeper'/388006, l='MpServer', x=1558.50, y=22.00, z=684.50], EntityCow['Cow'/279969, l='MpServer', x=1531.18, y=63.21, z=836.18], EntityCow['Cow'/279971, l='MpServer', x=1588.62, y=62.63, z=820.33], EntitySkeleton['Skeleton'/395945, l='MpServer', x=1593.50, y=26.00, z=679.50], EntityZombie['Zombie'/391351, l='MpServer', x=1616.50, y=20.00, z=819.50], EntityBat['Bat'/395444, l='MpServer', x=1485.67, y=38.10, z=806.91], EntityItem['item.item.terraqueous.multifood.plum'/385974, l='MpServer', x=1576.10, y=66.00, z=759.98], EntityCreeper['Creeper'/393136, l='MpServer', x=1558.50, y=41.00, z=692.18], EntityCow['Cow'/183, l='MpServer', x=1579.31, y=63.00, z=792.01], EntityCow['Cow'/184, l='MpServer', x=1581.59, y=62.44, z=799.37], EntityItem['item.item.terraqueous.multifood.orange'/376005, l='MpServer', x=1546.91, y=70.00, z=740.77], EntityBat['Bat'/395207, l='MpServer', x=1556.10, y=22.81, z=684.62], EntityCow['Cow'/133312, l='MpServer', x=1521.77, y=63.00, z=794.51], EntityZombie['Zombie'/393159, l='MpServer', x=1584.50, y=26.00, z=679.50], EntityZombie['Zombie'/392134, l='MpServer', x=1616.50, y=19.00, z=813.50], EntityFallenKnight['Fallen Knight'/386767, l='MpServer', x=1564.57, y=65.00, z=776.23], EntityBabySkeleton['Baby Skeleton'/387022, l='MpServer', x=1566.25, y=65.00, z=774.49], EntityCreeper['Creeper'/389577, l='MpServer', x=1489.50, y=37.00, z=801.50], EntityCow['Cow'/207, l='MpServer', x=1589.56, y=62.56, z=785.57], EntityItem['item.item.terraqueous.multifood.plum'/390346, l='MpServer', x=1556.63, y=66.00, z=756.55], EntityConcussionCreeper['Concussion Creeper'/394709, l='MpServer', x=1525.50, y=12.00, z=741.50], EntityCow['Cow'/218, l='MpServer', x=1608.53, y=63.00, z=773.78], EntityEnderminy['Enderminy'/386270, l='MpServer', x=1526.18, y=65.00, z=798.89], EntityBat['Bat'/392666, l='MpServer', x=1575.30, y=20.58, z=806.75], EntityCow['Cow'/230, l='MpServer', x=1622.53, y=63.00, z=740.82], EntityItem['item.item.rottenFlesh'/388591, l='MpServer', x=1571.91, y=63.00, z=727.59], EntityItem['item.item.terraqueous.itemmain.leather.boot1'/388590, l='MpServer', x=1572.81, y=63.00, z=728.54], EntityBabySquid['Baby Squid'/393193, l='MpServer', x=1597.30, y=62.57, z=801.68], EntityBat['Bat'/395775, l='MpServer', x=1549.35, y=20.03, z=676.52]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Non-integrated multiplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:409)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2647)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:387)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1119486568 bytes (1067 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmx4096M -Xms4096M
    IntCache: cache: 2, tcache: 87, allocated: 4, tallocated: 105
    FML: MCP 9.23 Powered by Forge 12.16.1.1934 96 mods loaded, 96 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJA  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJA  FML{8.0.99.99} [Forge Mod Loader](forge-1.9-12.16.1.1934.jar) 
    UCHIJA  Forge{12.16.1.1934} [Minecraft Forge](forge-1.9-12.16.1.1934.jar) 
    UCHIJA  buildingbrickshooks{1.9-2.0.5} [Building Bricks Hooks](minecraft.jar) 
    UCHIJA  CodeChickenCore{2.0.1.59} [CodeChicken Core](minecraft.jar) 
    UCHIJA  playerstatscore{1.1.0} [Player Stats Core](minecraft.jar) 
    UCHIJA  bettercombatmod{1.2} [Better Combat]([MC_1.9]BetterCombat-1.2.jar) 
    UCHIJA  JEI{3.3.3.200} [Just Enough Items](jei_1.9-3.3.3.200 %281%29.jar) 
    UCHIJA  abyssalcraft{1.9.1.6} [AbyssalCraft](AbyssalCraft-1.9-1.9.1.6.jar) 
    UCHIJA  animalbikes{1.8} [Animal Bikes](AnimalBikes_1.9.0%2826mar16%29.jar) 
    UCHIJA  AnimalsPlus{1.7} [Animals Plus](AnimalsPlus-1.8.jar) 
    UCHIJA  babymobs{1.5} [Baby Mobs](BabyMobs-1.9-1.5.jar) 
    UCHIJA  basemetals{2.2.2} [Base Metals](BaseMetals_1.9-2.2.2.jar) 
    UCHIJA  Baubles{1.2.0.2} [Baubles](Baubles-1.9-1.2.0.2.jar) 
    UCHIJA  BetterFoliage{2.0.11} [Better Foliage](BetterFoliage-MC1.9-2.0.11.jar) 
    UCHIJA  BiomesOPlenty{4.0.2.2018} [Biomes O' Plenty](BiomesOPlenty-1.9-4.0.2.2018-universal.jar) 
    UCHIJA  BloodMagic{1.9-2.0.0-38} [Blood Magic: Alchemical Wizardry](BloodMagic-1.9-2.0.0-38.jar) 
    UCHIJA  Botania{r1.8-305} [Botania](Botania-unofficial.r1.8-305.jar) 
    UCHIJA  Quark{beta-18} [Quark](Quark-beta-18.jar) 
    UCHIJA  buildingbricks{1.9-2.0.5} [Building Bricks](BuildingBricks-1.9-2.0.5.jar) 
    UCHIJA  Chameleon{1.9-2.1.3} [Chameleon](Chameleon-1.9-2.1.3.jar) 
    UCHIJA  Chimneys{1.9} [Chimneys](Chimneys-1.9-3.jar) 
    UCHIJA  chisel{@VERSION@} [Chisel](Chisel-MC1.9-0.0.4.14.jar) 
    UCHIJA  chiselsandbits{9.18} [Chisels & Bits](chiselsandbits-9.18.jar) 
    UCHIJA  decorationmegapack{1.9.4} [Decoration Mega Pack](decorationmegapack-19410009775.zip) 
    UCHIJA  DynamicLights{1.4.1} [Dynamic Lights](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_onFire{1.0.7} [Dynamic Lights Burning Entity Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_creepers{1.0.6} [Dynamic Lights Creeper Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_dropItems{1.1.0} [Dynamic Lights EntityItem Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_mobEquipment{1.1.0} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_flameArrows{1.0.1} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_floodLights{1.0.3} [Dynamic Lights Flood Light](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_otherPlayers{1.0.9} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.9.jar) 
    UCHIJA  DynamicLights_thePlayer{1.1.3} [Dynamic Lights Player Light Module](DynamicLights-1.9.jar) 
    UCHIJA  eggs{1.0} [Eat the Eggs!](Eat the Eggs-1.9-0.9 beta.jar) 
    UCHIJA  enchiridion{3.1.1} [Enchiridion](Enchiridion-1.9-3.1.1.jar) 
    UCHIJA  enderutilities{0.6.0} [Ender Utilities](enderutilities-1.9-0.6.0.jar) 
    UCHIJA  EnderZoo{1.9-1.2.1.39} [Ender Zoo](EnderZoo-1.9-1.2.1.39.jar) 
    UCHIJA  excore{1.5.3} [EXCore](Excore-1.5.3-1.9.jar) 
    UCHIJA  ezstorage{1.0} [EZ Storage](ezstorage-1.9-1.2.1.jar) 
    UCHIJA  ezextended{1.0.1} [EZ Extended](ezextended-1.0.1-[1.9].jar) 
    UCHIJA  FastLeaveDecay{1.1} [Fast Leave Decay](FastLeafDecay-MC1.9-1.2.jar) 
    UCHIJA  substratum{1.3.0.0} [Substratum](Substratum-1.9-1.3.0.0.jar) 
    UCHIJA  foundry{2.0.0.0-alpha3} [Foundry](Foundry-1.9-2.0.0.0-alpha3.jar) 
    UCHIJA  lit{1.9-1.0.15} [Little Insignificant Things](LittleInsignificantThings-1.9-1.0.15.jar) 
    UCHIJA  SilentLib{1.0.7} [Silent Lib](SilentLib-1.9-1.0.7-13.jar) 
    UCHIJA  SilentGems{2.0.11} [Silent's Gems](SilentsGems-1.9-2.0.11-29.jar) 
    UCHIJA  gemulation{1.9-2.0.6} [Gemulation](gemulation-1.9-2.0.6.jar) 
    UCHIJA  grapple_hooks{1.0.8} [Grapple Hooks](Grapple Hooks-1.9-1.0.8.jar) 
    UCHIJA  InventoryPets{1.4.6.1} [Inventory Pets](inventorypets-1.4.6.1.jar) 
    UCHIJA  IronChest{6.0.133.777} [Iron Chest](ironchest-1.9-6.0.133.777.jar) 
    UCHIJA  fyberbackpack{1.0.1} [Just Backpacks](justbackpacks-mc1.9-1.0.1.jar) 
    UCHIJA  jet_packs{1.0.0} [Just JetPacks](JustJetpacks-1.0.0.jar) 
    UCHIJA  lteleporters{1.1.1} [Lemon's Simple Teleporters](LemonsSimpleTeleporters-1.1.1.jar) 
    UCHIJA  Lux{1.5.0} [Lux](Lux-1.9-1.5.0.jar) 
    UCHIJA  malisiscore{1.9-3.0.6} [MalisisCore](malisiscore-1.9-3.0.6.jar) 
    UCHIJA  malisisblocks{1.9-3.0.1} [Malisis Blocks](malisisblocks-1.9-3.0.1.jar) 
    UCHIJA  malisisdoors{1.9-4.0.1} [MalisisDoors](malisisdoors-1.9-4.0.1.jar) 
    UCHIJA  mantle{1.9-0.10.1.jenkins141} [Mantle](Mantle-1.9-0.10.1.jar) 
    UCHIJA  MapWriter{2.4.19} [MapWriter](MapWriter-1.9-2.4.19.jar) 
    UCHIJA  RadixCore{1.9-2.1.0} [RadixCore](RadixCore-1.9-2.1.0-universal.jar) 
    UCHIJA  MCA{1.9-5.1.3} [Minecraft Comes Alive](MCA-1.9-5.1.3-universal.jar) 
    UCHIJA  modernmetals{0.9.2.3} [Modern Metals](ModernMetals-0.9.2.3.jar) 
    UCHIJA  moon-core{2.0} [Moon's Core](MoonCore%282.0%29 1.9.jar) 
    UCHIJA  shetiphiancore{3.2.5} [ShetiPhian-Core](shetiphiancore-1.9.0-3.2.5.jar) 
    UCHIJA  multibeds{1.1.1} [Multi-Beds](multibeds-1.9.0-1.1.1.jar) 
    UCHIJA  terraqueous{1.1.2.2} [Terraqueous](terraqueous-1.9.0-1.1.2.2.jar) 
    UCHIJA  multistorage{1.1.1.1} [Multi-Storage](multistorage-1.9.0-1.1.1.1.jar) 
    UCHIJA  nethercore{1.9-2.0.1} [Nether Core](nethercore-1.9-2.0.1.jar) 
    UCHIJA  recipehandler{0.4} [NoMoreRecipeConflict](NoMoreRecipeConflict-0.4%281.9%29 %282%29.jar) 
    UCHIJA  harvestcraft{1.9a} [Pam's HarvestCraft](Pam's HarvestCraft 1.9b.jar) 
    UCHIJA  pattysmoretools{1.0} [PattysMoreTools](PattysMoreTools2-1.9-1.1.jar) 
    UCHIJA  PigManure{1.0.2} [Pig Manure](pig-manure-1.0.2-mc1.9.jar) 
    UCHIJA  plantmegapack{1.9.8} [Plant Mega Pack](plantmegapack-19810001118.zip) 
    UCHIJA  platforms{1.1.0} [Platforms](platforms-1.9.0-1.1.0.jar) 
    UCHIJA  playerstats{1.1.0} [Player Stats](PlayerStats_1.9-1.1.0.jar) 
    UCHIJA  progression{0.5.2} [Progression](Progression-1.9-0.5.2.jar) 
    UCHIJA  progressiveautomation{1.6.44} [Progressive Automation](ProgressiveAutomation-1.9-1.6.44.jar) 
    UCHIJA  RandomUtilities{3.0.2} [Random Utilities](Random Utilities-1.9-3.0.3.jar) 
    UCHIJA  randomthings{3.7} [Random Things](RandomThings-MC1.9-3.7.jar) 
    UCHIJA  xreliquary{1.9-1.3.2.369} [Reliquary](Reliquary-1.9-1.3.2.369.jar) 
    UCHIJA  rftools{4.48} [RFTools](rftools-1.9.0-4.48.jar) 
    UCHIJA  rftoolsdim{4.23beta38} [RFTools Dimensions](rftoolsdim-1.9.0-4.23beta38.jar) 
    UCHIJA  RTG{1.9-2.0.0-alpha.4} [Realistic Terrain Generation](RTG-1.9-2.0.0-alpha.4.jar) 
    UCHIJA  SGExtraParts{1.0.0} [Silent's Gems: Extra Parts](SGExtraParts-1.9-1.0.0-1.jar) 
    UCHIJA  SimpleUpgrades{2.0.2} [SimpleUpgrades](simpleupgrades-1.9-2.0.2-release.jar) 
    UCHIJA  soggytransportation{1.9-RB2} [§bSoggyMustache's Transportation](soggytransportation-17.0.0%281.9%29.jar) 
    UCHIJA  soulshardstow{1.9-2.3.10-26} [Soul Shards - The Old Ways](SoulShards-TOW-1.9-2.3.10-26.jar) 
    UCHIJA  StorageDrawers{1.9-3.1.6} [Storage Drawers](StorageDrawers-1.9-3.1.6.jar) 
    UCHIJA  tconstruct{1.9-2.3.1.jenkins227} [Tinkers' Construct](TConstruct-1.9-2.3.1a.jar) 
    UCHIJA  TinkersAddons{1.0.1} [Tinkers' Addons](Tinkers' Addons-1.9-1.0.1.jar) 
    UCHIJA  ultimate_unicorn_mod{1.4.15} [Wings, Horns, and Hooves, the Ultimate Unicorn Mod!](ultimate_unicorn_mod-1.9-1.4.15.jar) 
    UCHIJA  vending{1.3.1} [vending](vending-1.9-1.3.4.jar) 
    UCHIJA  Waila{1.7.0} [Waila](Waila-1.7.0-B2_1.9 %282%29.jar) 
    UCHIJA  WailaHarvestability{1.1.7} [Waila Harvestability](WailaHarvestability-mc1.9-1.1.7 %281%29.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.9-3.7.jar)
  lumien.randomthings.asm.ClassTransformer
ProgressionTransformer (Progression-1.9-0.5.2.jar)
  joshie.progression.asm.ProgressionTransformer
CodeChickenCorePlugin (CodeChickenCore-1.9-2.0.1.59-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
LoadingPluginBuildingBricks (BuildingBricks-1.9-2.0.5.jar)
  com.hea3ven.buildingbricks.core.load.ClassTransformerBuildingBricks
CCLCorePlugin (CodeChickenLib-1.9-2.0.1.29-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
LoadingPlugin (Quark-beta-18.jar)
  vazkii.quark.base.asm.ClassTransformer
Player Stats Core (PlayerStats_1.9-1.1.0.jar)
  mrdimka.playerstats.core.CoreClassTransformer
CCCDeobfPlugin (unknown)

ShetiPhian-ASM (shetiphiancore-1.9.0-3.2.5.jar)
  shetiphian.core.asm.ClassTransformer
BetterFoliageLoader (BetterFoliage-MC1.9-2.0.11.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
MalisisCorePlugin (malisiscore-1.9-3.0.6.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
LoadingPlugin (FastLeafDecay-MC1.9-1.2.jar)
  lumien.fastleavedecay.asm.ClassTransformer
DLFMLCorePlugin (DynamicLights-1.9.jar)
  atomicstryker.dynamiclights.common.DLTransformer
    GL info: ' Vendor: 'Intel' Version: '4.4.0 - Build 10.18.15.4281' Renderer: 'Intel(R) HD Graphics 520'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - chiselsandbitsIntegration (Enabled/Not Forced)

```
Launched Version: 1.9-forge1.9-12.16.1.1934
LWJGL: 2.9.4
OpenGL: Intel(R) HD Graphics 520 GL version 4.4.0 - Build 10.18.15.4281, Intel
GL Caps: Using GL 1.3 multitexturing.
```

Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

```
Using VBOs: Yes
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: 
Current Language: English (US)
Profiler Position: N/A (disabled)
CPU: 4x Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
```

**Comment by joshiejack** [comment]
You shouldn't really be trying to match nbt on stacks that don't have nbt. I'll add checks though.Oh and since this is 1.9, you'll just have to avoid doing it. (To fix existing ones, you'd have to go edit the json manually and change any matchNBT where you made the error to false). Only supporting 1.8.9 and 1.9.4.
