### ISSUE TITLE
1.7.10 update

### ISSUE THREAD

**Issue by FilipK-CZ** [joshiejack/Progression#63]
Hi, can you do update for 1.7.10? Progression is good mod, but i can't update modpack to 1.8 or 1.9.
Repair disableCraftingUntilRewardAdded please

**Comment by joshiejack** [comment]
I have no time to support such an old version as well, with as many differences as it has sorry

**Comment by joshiejack** [comment]
I have no time to support such an old version as well, with as many differences as it has sorry

**Comment by FilipK-CZ** [comment]
I think that 1.7.10 it isn't too much old. If you have time please update it :) it is awesome mod

**Comment by joshiejack** [comment]
Two years and three versions behind isn't old?

**Comment by FilipK-CZ** [comment]
May be, but most mods are only on 1.7.10 and they are still active

**Comment by joshiejack** [comment]
hmm, everyone i know has dropped 1.7.10 support. Just because there are more mods available doesn't mean it's what you develop on. There is more because it is old.
