### ISSUE TITLE
[1.10.2] "Joined [team name]" won't go away

### ISSUE THREAD

**Issue by C0rn3j** [joshiejack/Progression#69]
Progression-1.10.2-0.6.7.jar

http://i.imgur.com/CtsrR9e.png

Simply won't go away even after changing team name.

**Comment by SeriousCreeper** [comment]
I've noticed that too, "Joined Single Player" doesn't go away and sometimes when i finished a quest, the "New Criteria" popup doesn't go away either it seems (manual claiming was set to false).

Also version Progression-1.10.2-0.6.7

**Comment by joshiejack** [comment]
I haven't forgotten about this. I'll try to get back to fixing these things next week.

**Comment by TymonDomanko** [comment]
This bug seems to be arising still when Better Achievements is present.

**Comment by joshiejack** [comment]
They override the vanilla system and use their own local variables instead of the underlying vanilla ones, so makes sense why it wouldn't work.
