### ISSUE TITLE
Crash when opening the editor

### ISSUE THREAD

**Issue by Janivire** [joshiejack/Progression#72]
So, this is for 1.7.10. an old version i know. however, recently ive been getting this crash every time i try and open the editor. ive also tried taking out each of the mods i have one at a time but that has had no success.

---- Minecraft Crash Report ----
// Would you like a cupcake?

Time: 8/6/16 10:48 PM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
    at joshie.progression.gui.GuiTreeEditor.drawForeground(GuiTreeEditor.java:100)
    at joshie.progression.gui.GuiBase.func_73863_a(GuiBase.java:64)
    at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1358)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1001)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at joshie.progression.gui.GuiTreeEditor.drawForeground(GuiTreeEditor.java:100)
    at joshie.progression.gui.GuiBase.func_73863_a(GuiBase.java:64)

-- Screen render details --
Details:
    Screen name: joshie.progression.gui.GuiTreeEditor
    Mouse location: Scaled: (341, 176). Absolute: (683, 353)
    Screen size: Scaled: (683, 353). Absolute: (1366, 706). Scale factor of 2

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['eruraion'/22, l='MpServer', x=-209.59, y=24.48, z=-849.64]]
    Chunk stats: MultiplayerChunkCache: 289, 298
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-308,4,-830), Chunk: (at 12,0,2 in -20,-52; contains blocks -320,0,-832 to -305,255,-817), Region: (-1,-2; contains chunks -32,-64 to -1,-33, blocks -512,0,-1024 to -1,255,-513)
    Level time: 1500896 game time, 1640944 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 2 total; [ReplicatorEntity['Replicator'/20, l='MpServer', x=-150.38, y=4.00, z=-887.41], EntityClientPlayerMP['eruraion'/22, l='MpServer', x=-209.59, y=24.48, z=-849.64]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 7 (amd64) version 6.1
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 534148088 bytes (509 MB) / 1343930368 bytes (1281 MB) up to 2040135680 bytes (1945 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1481 Optifine OptiFine_1.7.10_HD_U_C1 60 mods loaded, 59 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAA mcp{9.05} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAA FML{7.10.99.99} [Forge Mod Loader](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAAAA Forge{10.13.4.1481} [Minecraft Forge](forge-1.7.10-10.13.4.1481-1.7.10.jar) 
    UCHIJAAAAAA bettersleepingcore{1.0} [Better Sleeping Core](minecraft.jar) 
    UCHIJAAAAAA CodeChickenCore{1.0.4.29} [CodeChicken Core](minecraft.jar) 
    UCHIJAAAAAA ivtoolkit{IvToolkit} [1.2](minecraft.jar) 
    UCHIJAAAAAA NotEnoughItems{1.0.3.74} [Not Enough Items](NotEnoughItems-1.7.10-1.0.3.74-universal.jar) 
    UCHIJAAAAAA DungeonTools{2.1.0} [Dungeon Tools](1.7.10-DungeonTools-v2.1.1.jar.zip) 
    UCHIJAAAAAA DamageIndicatorsMod{3.2.0} [Damage Indicators]([1.7.10]DamageIndicatorsMod-3.2.0.jar) 
    UCHIJAAAAAA hud{1.3.5} [Better HUD](Better HUD by NukeDuck [1.7.10][1.3.5].jar) 
    UCHIJAAAAAA bettersleeping{1.7.10-0.8.22} [Better Sleeping](BetterSleeping-1.7.10-0.8.1.jar) 
    UCHIJAAAAAA betterstorage{0.11.1.121} [BetterStorage](BetterStorage-1.7.10-0.11.1.121.jar) 
    UCHIJAAAAAA BiomeTweaker{2.0.152} [BiomeTweaker](BiomeTweaker-1.7.10-2.0.152.jar) 
    UCHIJAAAAAA BuildCraft|Core{7.0.13} [BuildCraft](buildcraft-7.0.13-core.jar) 
    UCHIJAAAAAA BuildCraft|Factory{7.0.13} [BuildCraft Factory](buildcraft-7.0.13-factory.jar) 
    UCHIJAAAAAA BuildCraft|Transport{7.0.13} [Buildcraft Transport](buildcraft-7.0.13-transport.jar) 
    UCHIJAAAAAA cannibalism{1.1.1} [Cannibalism](Cannibalism-1.1.1-1.7.10.jar) 
    UCHIJAAAAAA CustomMainMenu{1.8} [Custom Main Menu](custommainmenu-mc1.7.10-1.8.jar) 
    UCHIJAAAAAA customnpcs{1.7.10c} [CustomNpcs](CustomNPCs_1.7.10c.jar) 
    UCHIJAAAAAA DescriptionTags{1.0} [Description Tags](DescriptionTags-1.0-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights{1.3.9} [Dynamic Lights](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_onFire{1.0.5} [Dynamic Lights Burning Entity Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module](DynamicLights-1.7.10.jar) 
    UCHIJAAAAAA Eln{48} [Electrical Age](ElectricalAge_BETA-1.10_r49.jar) 
    UCHIJAAAAAA enviromine{1.3.118} [EnviroMine](EnviroMine-1.3.118.jar) 
    UCHIJAAAAAA FalloutSalvage{1.1.5} [FalloutSalvage](FalloutSalvage.zip) 
    UCHIJAAAAAA flansmod{4.9.0} [Flan's Mod](Flans Mod-1.7.10-4.9.0.jar) 
    UCHIJAAAAAA glass_shards{1.3.2} [Glass Shards](glass_shards_mc1.7.10-1.3.2.jar) 
    UCHIJAAAAAA GlobalGameRules{{}} [Global GameRules](GlobalGameRules-1.0.jar) 
    UCHIJAAAAAA hostagemod{0.1.2} [Hostage Mod](HostageMod-0.1.2.jar) 
    UCHIJAAAAAA IguanaTweaks{2A} [Iguana Tweaks](IguanaTweaks-1.7.10-2A.jar) 
    UCHIJAAAAAA infiniteinvo{1.0.44} [InfiniteInvo](InfiniteInvo-1.0.44.jar) 
    UCHIJAAAAAA malisiscore{1.7.10-0.14.3} [MalisisCore](malisiscore-1.7.10-0.14.3.jar) 
    UCHIJAAAAAA malisisdoors{1.7.10-1.13.2} [Malisis' Doors](malisisdoors-1.7.10-1.13.2.jar) 
    UCHIJAAAAAA RadixCore{2.0.2} [RadixCore](RadixCore-2.0.2-1.7.10-universal.jar) 
    UCHIJAAAAAA MCA{5.0.6} [Minecraft Comes Alive](MCA-5.0.6-1.7.10-universal.jar) 
    UCHIJAAAAAA minestones{1.7.10-MS1.0.1} [Minestones](minestones-1.7.10-MS1.0.1.jar) 
    UCHIJAAAAAA MineTweaker3{3.0.9B} [MineTweaker 3](MineTweaker3-1.7.10-3.0.9C.jar) 
    UCHIJAAAAAA MTRM{1.0} [MineTweakerRecipeMaker](MineTweakerRecipeMaker-1.7.10-1.1.0.11.jar) 
    UCHIJAAAAAA examplemod{1.0} [examplemod](More Health Enchanted-1.7.10-6.3.jar) 
    UCHIJAAAAAA morehealth{6.3} [More Health Forge](More Health Enchanted-1.7.10-6.3.jar) 
    UCHIJAAAAAA cfm{3.4.7} [§9MrCrayfish's Furniture Mod](MrCrayfishFurnitureModv3.4.7%281.7.10%29.jar) 
    UCHIJAAAAAA mztraders{0.0.1} [MZTraders Mod](MZTraders-1.0.2.jar) 
    UCHIJAAAAAA pennyarcade{Alpha 1.2} [Penny Arcade Mod](Penny Arcade Mod Alpha 1.2.jar) 
    UCHIJAAAAAA Progression{0.4.1} [Progression](Progression-1.7.10-0.4.1.jar) 
    UCHIJAAAAAA reccomplex{0.9.6.3} [Recurrent Complex](RecurrentComplex-0.9.6.3.jar) 
    UCHIJAAAAAA shouldersurfing{1.0} [ShoulderSurfing](shouldersurfing-1.7.10.jar) 
    UCHIJAAAAAA simplefluidtanks{1.7.10-1.2.0.5} [Simple Fluid Tanks](simplefluidtanks-1.7.10-1.2.0.5.jar) 
    UCHIJAAAAAA teaminfo{1.0} [TeamInfo](TeamInfo-1.7.10-1.0.jar) 
    UCHIJAAAAAA tradeboothmod{1.7.10.2} [tradeboothmod](tradebooth.1.7.10.2.jar) 
    UCHIJAAAAAA AS_UpdateCheck{1.1.7} [AtomicStryker Update Check Mod](UpdateCheckerMod-1.7.10.jar) 
    UCHIJAAAAAA YouShallNotStack{1.1} [YouShallNotStack](YouShallNotStack-1.1.jar) 
    UD  BiomeTweakerCore{2.0.152} [BiomeTweaker Core](minecraft.jar) 
    GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.1.10834 Compatibility Profile Context' Renderer: 'AMD Radeon HD 6320M '
    Launched Version: 1.7.10-Forge10.13.4.1481-1.7.10
    LWJGL: 2.9.1
    OpenGL: AMD Radeon HD 6320M  GL version 4.1.10834 Compatibility Profile Context, ATI Technologies Inc.
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: [Fallout server pack]
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by joshiejack** [comment]
I'm pretty much done with progression, let alone the 1.7 version.
