### ISSUE TITLE
Suggestion: mod activator/deactivator

### ISSUE THREAD

**Issue by lightning02** [joshiejack/Progression#73]
Hello, I've tryed your mod, it is very beautiful and useful!
Anyway, I didn't find any way in order to disable entire mods unitl a certain achievement is reached so far..
Did I missed something? Is this a feature that is missing and could be implemented?
I hope I'm not bothering you asking this.. :o

**Comment by joshiejack** [comment]
That's entirely possible. There's mod filters, and achievement tasks. Although blocking things is kinda lackluster tbh, since it only works with certain forms of crafting. So you'd have to watch out for ways around the system.

**Comment by lightning02** [comment]
Do you mean that I have to do this only by blocking the mod's craftings instead of the mod itself? :O

**Comment by joshiejack** [comment]
What? Yes? How else would that work?

**Comment by lightning02** [comment]
I was hoping something like: for example "condition: craft item X  ----> result: unlock an entire mod with its craftings"
it would be less time consuming somehow

**Comment by joshiejack** [comment]
That's literally just what I said you do.

**Comment by lightning02** [comment]
ohw... mhm... but...  how? I mean.. 
ok let me ask last thing just for confirmation >_<
for example, I'm gonna try to unlock mekanism for players when they craft 16 technical blocks from chisel.. I'm supposed to use that option called modid, right?
kinda like here
http://imgur.com/UpLMvT4
and this will unlock all mekanism crafting? or I have to add them one by one like I've made for metallurgic infuser (in the screenshot)

**Comment by joshiejack** [comment]
Oh you're using 1.7, >.>

**Comment by lightning02** [comment]
Ehm... yes? °-°
1.7.10 is the milestone for modding..still
Isn't supposed to work the mod-filter for progression 1.7.10?

**Comment by joshiejack** [comment]
The 1.7 version is unsupported. And also incredibly outdated, it's very broken. You're better off just not using the mod. It can't do half the things the newer versions can.

**Comment by lightning02** [comment]
Can I ask why you decided to dump support for 1.7.10 btw? :O

**Comment by joshiejack** [comment]
... Because there is no point/benefit to me in wasting my time on a modded version that is three versions out of date. With an ENTIRELY different codebase. And is seriously EOL. When I should be spending my time on my other mods for newer versions. I don't have the time. And even if I did, I would not be supporting such a far outdated version. It's even killing me having to support 1.8 as is for this mod.

**Comment by lightning02** [comment]
It's EOL because Forge team decided to dump support for it, but the idea, the concept of remain on a version like 1.7.10 and mod for it (as a official modding version where to develop mods) had a great sense and has a sense even right now.. I can understand your decision, there are plenty new possibility in modding with newer version of minecraft, but the fact is that mojang this way is fracturing the community and split it over and over, few modpacks are decent in the newer versions, because most of the mods remain behind.. According to fix, a stop, in a determinate version as the "modding version for minecraft" until a new stable version is out that may can persist 1-2 years was a good decision and it is also by now. Some mods are still being developed for 1.7.10. and this is a good thing fortunately.
What I mean is that you waste even more time on coding and re-coding your mods for every version that mojang pulls out...
But well, you already chosed to follow forge, as some other mod developers did, and the only thing I can do is respect your decision, sadly

**Comment by joshiejack** [comment]
I'd hardly call it wasting my time. When it's for my own enjoyment. I've not played 1.7 in a long time now. Played on 1.9/1.10 server.
