### ISSUE TITLE
Issue on Server

### ISSUE THREAD

**Issue by BLSK** [joshiejack/Progression#8]
Hello joshiejack,
"Using Progression 3.5" (will try a lower version in case it may work...worth a shot)
I found your mod and was like cool so messing around on Single player it is looking neat...
Problem...
I am currently using a 1407 forge server and when I enable your mod on it crashes...at first I thought it may of been another mod but even disabling that mod which is stated in this crash report
http://pastebin.com/7ydUU5hH
it still crashes.  I hope you can help.  I really would like to see the mod in the modpack...its neat XD...still learning how to use it but yeah neat XD

If you would like more info like what mods I have brought together for the modpack as it may give you a more info...I'll tell ya of course... really itching to see how it will work on a server

**Comment by BLSK** [comment]
I have goofed...didn't even mean to grab 1407...was grabbing 1403 since the modpack I have been working on will use Forge Server not Cauldron...  I am testing out the progression thing again...  1407 wasn't cooperating as it maxing out any memory...not sure if that could be a contributing factor but yeah...minor oversight late at night XD

**Comment by BLSK** [comment]
Even changing it same issue.  About as much troubleshooting as I can do at the moment...
Just tell me what you need and I'll have it for ya lickety-split.(or tomorrow)

**Comment by joshiejack** [comment]
What's the crash without that mod.

**Comment by BLSK** [comment]
It hasn't been giving me a crash at least to my knowledge... for some reason it seemed MoreHealth was acting like a conduit.... for that report...
This is the server console data that keeps repeating if its any help?
http://pastebin.com/EZC6y5zN
its upsidedown...but yeah....its how the server console does it...  

In case it were relevant the modpack is public so I could just update a zip for you to look at since I believe all new mods are Open as I am fairly sure yours says so too.  I am not saying it is your mod 100% but it is some kind of incompatibility...  I just hope to get to have the modpack working properly XD

If you want of course I'll try to narrow down why the server is crashing by disabling mods in sections till the server works as to find what may be effecting it.

**Comment by BLSK** [comment]
Oh it could be unique as well to a modpack like mine...
Let me explain:
If I install the forge into a server with no other mods...My modpack will not be able to connect to it.
One of the mods which I am working to find out which seems to altar the FML or something just enough that with the mod in it, it says its an Incompatible FML Server.  I am not sure if that could be the cause of the issue but I am working out which mod it is.  If it were the issue and removing that mod fixed it so yours works great...but I do know that the Client works with your mod in it so yeah....kinda puzzling to me...I could be wrong on the whole FML thing but I thought you may like any details I could provide... not sure if helpful but I am working doing what I can for the moment.

I figure it would only take like another day for me to sort out things on the client to server FML thing.  I might be able to remove that mod but at the very least it may give you more insight...I have work soon enough so I may not get back here till after midnight US East.  as I said... I just would like to see things working XD...
Oh and...

Server Side Mods are:
ForgeEssentials
Slash
Dynmap
WorldEdit(also client has it now)(it is included in ForgeEssentials)

**Comment by joshiejack** [comment]
Update forge essentials.

**Comment by BLSK** [comment]
It's already the most updated version.  FE - 1.4.0 beta6 unless your meaning yours works with like beta5 or something?

**Comment by joshiejack** [comment]
No it's not.

https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1449
There's beta 7 in there.

The current version doesn't like coremods

**Comment by BLSK** [comment]
ok cool sorry...going to go grab the beta 7...  Thank you very much for the help...

**Comment by BLSK** [comment]
Turns out the new beta(unless there is another) crashes on startup on its own...Thanks a million though for directing the issue to the FE people.  Hopefully it will be corrected soon unless there is another download I can find...Thanks a lot.  Things should be very enjoyable with your mod added...
