### ISSUE TITLE
Progression Criterias refusing to accept changes

### ISSUE THREAD

**Issue by RexAnivius** [joshiejack/Progression#80]
Version: Progression-1.7.10-0.4.1

Details:
Tested in ssp - works fine.
Tested in smp (modded server with my friends) - does not seem to accept any changes I make (I am OPed on the server). I copied my ssp json file onto the server and it managed to load it and people can progress on it, but any adjustments I make along the way get reset back to the initial saved state. Please, if anyone knows what could cause this and perhaps how to fix it - let me know!

The entire server is running with 1.7.10 mods, so updating isn't quite an option for now, which is why I hope this issue is solvable without the need to update to the latest.

**Comment by adrwa** [comment]
1.7 is no longer supported
